// SPDX-License-Identifier: Apache-2.0
// EP Federation Operator 2 — PIP-006 federation surfaces (Supabase Edge Function).
// Generated by conformance/operator2/gen-operator2.mjs. Separately-deployed
// operator; NOT an independent third party (same owner) — see PIP-006.
import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const DISCOVERY = {
  "version": "1.1",
  "operator_id": "ep_operator_2_supabase_edge",
  "protocol_version": "EP-CORE-v1.0",
  "cache_ttl_seconds": 300,
  "verify_url_template": "https://kgknhhdqsykxcwzdfeim.supabase.co/functions/v1/operator2/api/verify/{receipt_id}",
  "keys": {
    "ep_operator_2_supabase_edge": {
      "public_key": "MCowBQYDK2VwAyEAKv3cp6u_P1lJOlSUziKZn2QpOrVAM5-FyWNVUYsgLZY",
      "algorithm": "Ed25519"
    }
  },
  "historical_keys": {}
};
const RECEIPT = {
  "@version": "EP-RECEIPT-v1",
  "payload": {
    "receipt_id": "ep_receipt_operator2_demo_001",
    "@version": "EP-RECEIPT-v1",
    "entity_id": "ep_entity_operator2_demo_agent",
    "action": {
      "type": "fin/payment-release",
      "amount": 42000,
      "currency": "USD"
    },
    "context": {
      "risk_signals": [
        "cross_operator_demo"
      ]
    },
    "issued_at": "2026-06-11T00:00:00Z",
    "issuer_operator": "ep_operator_2_supabase_edge"
  },
  "signature": {
    "signer": "ep_operator_2_supabase_edge",
    "key_discovery": "https://kgknhhdqsykxcwzdfeim.supabase.co/functions/v1/operator2/.well-known/ep-keys.json",
    "algorithm": "Ed25519",
    "value": "VRPnFqyuuxZQKY3s4MaIy4-4buu0wYfjPXw4LIEmrYhGN-GEX_Aj3uFelOCB_q3k--xk6tNlMZUL4ISw5arpCw"
  }
};
const J = (b: unknown) => new Response(JSON.stringify(b), { headers: { "content-type": "application/json", "access-control-allow-origin": "*", "cache-control": "public, max-age=300" } });

Deno.serve((req: Request) => {
  // Prefix-agnostic routing: Supabase may present the path with or without the
  // /functions/v1/operator2 prefix, so match on the suffix.
  const path = new URL(req.url).pathname;
  if (path.endsWith("/ep-keys.json")) return J(DISCOVERY);
  if (path.endsWith("/receipt") || path.endsWith("/sample-receipt")) return J(RECEIPT);
  const vm = path.match(/\/api\/verify\/([^/]+)$/);
  if (vm) return J({ receipt_id: decodeURIComponent(vm[1]), revoked: false, revocation: { revoked: false, checked: true, basis: "operator 2 revocation list (empty)" } });
  return J({ operator_id: DISCOVERY.operator_id, surfaces: ["/.well-known/ep-keys.json", "/receipt", "/api/verify/{receipt_id}"] });
});
