// SPDX-License-Identifier: Apache-2.0
//
// Human-reviewed source data for the Consequential Action Interoperability
// Project. These are candidate mappings, not author endorsements.

const p = (operation, target, parameters, _audience) => ({
  operation,
  target,
  parameters,
});

export const targets = [
  {
    draft: 'draft-klrc-aiagent-auth',
    revision: '03',
    title: 'AI Agent Authentication and Authorization',
    source_sha256: '41b3899039a6c978c69eed32b17485a72f6dfef72c96d38eec9bbe9b0190e37a',
    native_binding: 'PARTIAL',
    missing_material_fields: ['parameters_digest'],
    paths: p('/audit/action', '/audit/resource', '/mission/parameters', '/transaction_token/audience'),
    evidence: ['Sections 10.1, 10.4, 10.5, and 10.7, pages 13-18', 'Missions, OAuth delegation, transaction tokens, and human confirmation are described, while mission translation remains out of scope.'],
    request: 'Please check whether the audit action/resource and transaction-token audience are the right extraction points, and whether a normative parameter commitment exists.',
  },
  {
    draft: 'draft-mcguinness-oauth-ai-agent-instance',
    revision: '00',
    title: 'OAuth 2.0 AI Agent Instance Profile',
    source_sha256: '347ae484d4c18d35d166281921bc7860b1ca4d9847db125d9fa917a7142fa476',
    native_binding: 'ABSENT',
    missing_material_fields: ['operation', 'target_ref', 'parameters_digest'],
    paths: p('/scope/operation', '/scope/resource', '/scope/parameters', '/aud'),
    evidence: ['Sections 9-11, pages 13-14', 'The profile binds agent-instance and delegation evidence, but not a complete consequential action target and parameter set.'],
    request: 'Please check whether any profile claim can supply a stable target and parameter commitment without treating agent identity as action authority.',
  },
  {
    draft: 'draft-noa-scitt-ai-agent-receipt',
    revision: '00',
    title: 'A SCITT Profile for AI-Agent Action Receipts',
    source_sha256: '10e5d7ade5a7650348f85dac357c2db449d8329e2700ad0cf5ee8b3a1e0a921d',
    native_binding: 'PARTIAL',
    missing_material_fields: ['target_ref', 'parameters_digest'],
    paths: p('/action/canonical', '/action/id', '/action/parameters', '/scope/tenant'),
    evidence: ['Sections 3-4, action receipt payload', 'The receipt carries action identity, a canonical risk-table key, parameter commitment, and tenant-scoped chain context.'],
    request: 'Please check whether action.id is the correct material target and whether action.paramsHash should be mapped directly rather than re-derived from disclosed parameters.',
  },
  {
    draft: 'draft-ietf-wimse-arch',
    revision: '08',
    title: 'Workload Identity in a Multi System Environment (WIMSE) Architecture',
    source_sha256: '5577c6a92d6f6b9ebf70d7da61365cf777277534ab0c3c2aa7f4698a1b4541f4',
    native_binding: 'ABSENT',
    missing_material_fields: ['operation', 'target_ref', 'parameters_digest'],
    paths: p('/security_context/operation', '/security_context/target', '/security_context/parameters', '/security_context/audience'),
    evidence: ['Sections 3.3-3.4.7, pages 15-26', 'The architecture separates authentication from authorization and intentionally leaves message-level authorization formats out of scope.'],
    request: 'Please check whether a WIMSE security-context profile is the correct place to carry an external exact-action reference.',
  },
  {
    draft: 'draft-ietf-wimse-http-signature',
    revision: '05',
    title: 'WIMSE Workload-to-Workload Authentication with HTTP Signatures',
    source_sha256: '96ae3e18caf3ce05229e4d789ffd3eff847cba7984710f86c85d5677113fadfc',
    native_binding: 'COMPLETE',
    missing_material_fields: [],
    paths: p('/signed_components/@method', '/signed_components/@request-target', '/signed_components/body', '/signature_params/wimse-aud'),
    evidence: ['Sections 3-3.3, pages 4-7', 'The profile covers the request method and target, Content-Digest for bodies, audience, freshness, nonce, and request-response binding.'],
    request: 'Please check whether the covered HTTP method, target URI, body representation, and wimse-aud are sufficient material fields for an HTTP-action mapping.',
  },
  {
    draft: 'draft-ietf-wimse-workload-creds',
    revision: '02',
    title: 'WIMSE Workload Credentials',
    source_sha256: 'b111e4e85a7f3bc5c844560db87276c184a04db28ffeaccb057c13eb034dbed5',
    native_binding: 'ABSENT',
    missing_material_fields: ['operation', 'target_ref', 'parameters_digest'],
    paths: p('/authorization/operation', '/authorization/target', '/authorization/parameters', '/credential/audience'),
    evidence: ['Sections 3, 7, and 9.2-9.5', 'The draft establishes workload identity and proof-of-possession context, not an exact consequential action.'],
    request: 'Please check whether the credential should remain actor context only and point to an external action object.',
  },
  {
    draft: 'draft-ietf-wimse-wpt',
    revision: '01',
    title: 'WIMSE Workload Proof Token',
    source_sha256: 'a08af6270c8efd4a8320fb59e69bf29fe747ee14a4681be30aac9be45bf56e1e',
    native_binding: 'PARTIAL',
    missing_material_fields: ['parameters_digest'],
    paths: p('/request/method', '/request/target', '/request/parameters', '/claims/aud'),
    evidence: ['Sections 3.1-3.4', 'The token binds workload proof and request context, but unprotected request material and middleboxes limit exact-action coverage.'],
    request: 'Please check which request components are guaranteed protected and whether a body or parameter commitment belongs in a companion profile.',
  },
  {
    draft: 'draft-bu-agentproto-security-principal-binding',
    revision: '03',
    title: 'Security Principal and Verifier Binding for Agent Communication Protocols',
    source_sha256: '52928b5e2384b981cdd69cb7178312eea588c5a63a18428bca8692a4d69e3f86',
    native_binding: 'ABSENT',
    missing_material_fields: ['operation', 'target_ref', 'parameters_digest'],
    paths: p('/action/operation', '/action/target', '/action/parameters', '/action/audience'),
    evidence: ['Sections 18-22, pages 21-31', 'The draft defines composition slots and negative tests but intentionally does not instantiate a concrete action wire object.'],
    request: 'Please check whether this neutral extraction/carry split matches the verifier-matrix intent without privileging any protocol.',
  },
  {
    draft: 'draft-rosomakho-oauth-txn-challenge',
    revision: '00',
    title: 'OAuth Transaction Authorization Challenge',
    source_sha256: 'a50c1fee4ce4ae486aa6e6739e9927586dc5c14a209434f44f76200354a8cead',
    native_binding: 'COMPLETE',
    missing_material_fields: [],
    paths: p('/authorization_details/0/type', '/iss', '/caid_extraction/parameters', '/aud'),
    evidence: ['Sections 4.2.1-4.3, pages 9-12', 'The signed challenge carries transaction identity and RAR authorization details describing the challenged operation.'],
    request: 'Please check whether the first RAR item is a valid single-action extraction or whether profiles must reject multi-item challenges as indeterminate.',
  },
  {
    draft: 'draft-nelson-agent-delegation-receipts',
    revision: '10',
    title: 'Delegation Receipt Protocol for AI Agent Authorization',
    source_sha256: '08ba640802f461ed30e66f9b2cd7a50a3570b5838c39bf012c2b039ee2ed68bb',
    native_binding: 'PARTIAL',
    missing_material_fields: ['parameters_digest'],
    paths: p('/scope/operations/0', '/scope/resources/0', '/boundaries', '/audience'),
    evidence: ['Sections 4.1-6.4, pages 8-29', 'The receipt binds structured operations, resources, boundaries, timing, and signed pre-execution scope.'],
    request: 'Please check whether scope.resources and boundaries fully determine one consequential action or require an additional per-execution action commitment.',
  },
  {
    draft: 'draft-jiang-oauth-intent-admission',
    revision: '00',
    title: 'Intent Admission Assertions for Agentic Systems',
    source_sha256: 'd672a85cadaafccccf80489befa7018f6ffbdc749d361b1c8fe5d79468419867',
    native_binding: 'COMPLETE',
    missing_material_fields: [],
    paths: p('/authorization_details/0/actions/0', '/authorization_details/0/locations/0', '/authorization_details/0/constraints', '/aud'),
    evidence: ['Sections 4.1-5, pages 8-10', 'The assertion binds canonical intent, admitted action/resource scope, constraints, audience, and presenter proof before execution.'],
    request: 'Please check whether one ActionRef should cover a single action/resource pair and how multi-action admissions should be split or rejected.',
  },
  {
    draft: 'draft-araut-oauth-transaction-tokens-for-agents',
    revision: '02',
    title: 'Transaction Tokens For Agents',
    source_sha256: 'c69ce45480dfbd46f6972770a2adb7d99396db5333f3438ecdd1b2a215bf3234',
    native_binding: 'PARTIAL',
    missing_material_fields: ['parameters_digest'],
    paths: p('/transaction/operation', '/transaction/resource', '/transaction/parameters', '/aud'),
    evidence: ['Transaction Token claims and multi-agent examples', 'The token carries subject, actor, scope, and transaction context; the exact parameter commitment is not uniformly defined.'],
    request: 'Please check whether transaction context can normatively expose exact parameters or should carry an external action digest.',
  },
  {
    draft: 'draft-coetzee-oauth-spt-txn-tokens',
    revision: '03',
    title: 'Transaction-Bound Authorization Tokens for Software and AI Agents (SPT-Txn)',
    source_sha256: '5ebba0db429816a7fe887128f08d51c3840209bf17de74d66581ce935966e195',
    native_binding: 'PARTIAL',
    missing_material_fields: ['parameters_digest'],
    paths: p('/intent/tool', '/intent/target', '/intent/params', '/aud'),
    evidence: ['Sections 5.1-5.3, pages 8-9', 'Intent is defined by tool, target, and parameters with JCS-based canonicalization and SHA-256 digest checking.'],
    request: 'Please check whether audience is material to action identity or should remain verifier context outside the CAID projection.',
  },
  {
    draft: 'draft-mcguinness-oauth-actor-profile',
    revision: '00',
    title: 'OAuth Actor Profile for Delegation',
    source_sha256: 'd6b47ec71b32a6dcc9f22603925b95f3bce2b631041dcda0c8179eb6712c2dd9',
    native_binding: 'ABSENT',
    missing_material_fields: ['operation', 'target_ref', 'parameters_digest'],
    paths: p('/authorization/operation', '/authorization/target', '/authorization/parameters', '/aud'),
    evidence: ['Interoperability and permission-decision scope', 'The profile standardizes actor representation and propagation while leaving actor permissions and action semantics deployment-specific.'],
    request: 'Please check whether act-chain claims should remain authenticated actor context and reference a separate action object.',
  },
  {
    draft: 'draft-rampalli-cross-org-delegation-mapping',
    revision: '05',
    title: 'A Layered Requirements Mapping for Cross-Organization Agent Delegation',
    source_sha256: 'd1a8e0cd4cd59a8377a4949146a20c37457dab002e5d86bba343073798103bef',
    native_binding: 'PARTIAL',
    missing_material_fields: ['operation', 'target_ref', 'parameters_digest'],
    paths: p('/action/operation', '/action/target', '/action/parameters', '/relying_party/audience'),
    evidence: ['Sections 3-3.4, pages 8-13', 'The requirements model joins evidence by action digest but does not define the canonical action object that produced that digest.'],
    request: 'Please check whether the shared digest should carry a profile identifier so different canonicalizers cannot appear equivalent.',
  },
  {
    draft: 'draft-mih-scitt-agent-action-capsule-sel-disc',
    revision: '00',
    title: 'Selective Disclosure Profile for Agent Action Capsules',
    source_sha256: '7d06ae8ada91ca054336f200836755e15aec454c3fb5288d3d0457e6d8b1cd10',
    native_binding: 'PARTIAL',
    missing_material_fields: ['parameters_digest'],
    paths: p('/disclosed/action/type', '/disclosed/action/target', '/disclosed/action/parameters', '/recipient'),
    evidence: ['Sections 5.1-6.5, pages 10-15', 'Selective disclosure can omit fields; verification must distinguish intentionally undisclosed material from absent material.'],
    request: 'Please check which action fields must be disclosed before an exact-action equivalence result is permitted.',
  },
  {
    draft: 'draft-emirdag-scitt-ai-agent-execution',
    revision: '00',
    title: 'AI Agent Execution Profile of SCITT',
    source_sha256: '716a92dc5bb56e812aeaae5e3b7a7374c279957b4e88ad8eddc3c93695b2f836',
    native_binding: 'PARTIAL',
    missing_material_fields: ['parameters_digest'],
    paths: p('/air/action_category', '/air/target', '/air/parameters', '/air/principal'),
    evidence: ['Sections 3.1-3.3 and 6-7, pages 6 and 17-18', 'The AIR profile preserves execution and custody evidence but does not require a complete pre-execution parameter commitment.'],
    request: 'Please check whether intent_attestation or a companion reference is the right home for a canonical exact-action commitment.',
  },
  {
    draft: 'draft-lee-orprg-permit-receipts',
    revision: '00',
    title: 'Permit Receipts for Permit-Before-Commit Authorization of AI-Agent and Workload External Effects',
    source_sha256: 'ea164cf92f89490f8b9ad6c7accf0726f6b33cd72925c3bcc148cb7c65286bac',
    native_binding: 'PARTIAL',
    missing_material_fields: ['operation', 'target_ref', 'parameters_digest'],
    paths: p('/effect_request/operation', '/effect_request/target', '/effect_request/parameters', '/audience'),
    evidence: ['Sections 7-12, pages 7-12', 'The model canonicalizes the exact external-effect request and binds its digest, scope, audience, epoch, and validity.'],
    request: 'Please check the canonical effect-request field projection and whether policy epoch belongs outside action identity.',
  },
  {
    draft: 'draft-baur-pap',
    revision: '02',
    title: 'Principal Agent Protocol (PAP)',
    source_sha256: 'a0c97214df66689f8fb6b7206e8abf1efcc94a309044cbfe114c889c0f6c4535',
    native_binding: 'PARTIAL',
    missing_material_fields: ['parameters_digest'],
    paths: p('/scope/actions/0/action', '/scope/actions/0/object', '/scope/actions/0/conditions', '/capability/audience'),
    evidence: ['Sections 3.1-5.6, pages 8-18', 'PAP binds a principal-rooted mandate and single-use capability token to a structured action scope.'],
    request: 'Please check whether the capability action object has a stable target and parameter representation across PAP profiles.',
  },
  {
    draft: 'draft-pidlisnyi-aps',
    revision: '03',
    title: 'Agent Passport System (APS): Verifiable Agent Identity, Faceted Authority, and Signed Action Receipts',
    source_sha256: '59b9547a20c6d514eceb97d169b92b2f9c70a231f5b914e8fc1b478c7f359fca',
    native_binding: 'COMPLETE',
    missing_material_fields: [],
    paths: p('/action_ref/action_type', '/action_ref/target', '/action_ref/payload', '/action_ref/audience'),
    evidence: ['Sections 3.1-3.6 and 4.1-4.3, pages 8-17', 'ActionRefV2 commits to the requested action and payload under a named profile with single-use admission state.'],
    request: 'Please check the ActionRefV2 projection and whether principal identity is intentionally inside or outside the action reference.',
  },
  {
    draft: 'draft-howe-vcon-agent-session',
    revision: '00',
    title: 'vCon Agent Session',
    source_sha256: 'b88e60f74fc6737ceb4ffd230c2bfa49b5c5250b64b058bcd009b4b75a61c507',
    native_binding: 'PARTIAL',
    missing_material_fields: ['parameters_digest'],
    paths: p('/tool_call/name', '/tool_call/target', '/tool_call/arguments', '/parties/recipient'),
    evidence: ['Sections 8-11', 'The signed session envelope can record tool activity but does not require exact material fields for every consequential call.'],
    request: 'Please check whether a consequential tool-call attachment should require an action profile and parameters digest.',
  },
  {
    draft: 'draft-pei-opsawg-agentops-observability',
    revision: '00',
    title: 'AgentOps Observability for Failure Detection and Attribution',
    source_sha256: '00a060440ced78e138ac89a7ba65ad083880569febf78586dd937ade42c9e35c',
    native_binding: 'PARTIAL',
    missing_material_fields: ['parameters_digest'],
    paths: p('/event/action', '/event/resource', '/event/parameters', '/event/receiver'),
    evidence: ['Sections 4.1-4.5, pages 6-10', 'The event envelope covers actors, phases, causal links, and evidence references but not a mandatory exact parameter projection.'],
    request: 'Please check which event attributes are stable enough for exact-action extraction without exposing sensitive payloads.',
  },
  {
    draft: 'draft-dunbar-dmsc-gw-scenarios-gap-analysis',
    revision: '02',
    title: 'Deployment Scenarios and Gap Analysis for AI Agent Gateway',
    source_sha256: '17ebf5da730d45266e51052ee806d7d824539348ca89d362a7784e3d50d7c499',
    native_binding: 'ABSENT',
    missing_material_fields: ['operation', 'target_ref', 'parameters_digest'],
    paths: p('/authorization/operation', '/authorization/target', '/authorization/parameters', '/authorization/audience'),
    evidence: ['Sections 5.3-5.5 and 6.7-6.9, pages 19-27', 'The draft identifies gateway exchange and action-level authorization for physical-world operations as requirements, but no concrete action artifact is defined.'],
    request: 'Please check our reading of Sections 6.7 and 6.9: should a future DMSC profile carry a canonical action reference across gateway boundaries?',
  },
  {
    draft: 'draft-soden-wellknown-mcp-commerce',
    revision: '00',
    title: 'A Well-Known URI Profile for Agent-Callable Commerce Endpoints',
    source_sha256: 'd6e8a6119fe2797490afb6a4106ee57834ac1ac4761abe149d7666deb994a917',
    native_binding: 'ABSENT',
    missing_material_fields: ['operation', 'parameters_digest'],
    paths: p('/commerce/tool', '/commerce/endpoint', '/commerce/parameters', '/commerce/merchant'),
    evidence: ['Section 4, pages 9-10', 'Discovery identifies agent-callable commerce endpoints but leaves transaction authorization and exact invocation material to clients.'],
    request: 'Please check whether a commerce entry should advertise an action-schema or CAID profile for the selected MCP tool.',
  },
  {
    draft: 'draft-hopley-x402-compliance-receipt',
    revision: '02',
    title: 'Categorical Compliance Screening Receipt Format for Agentic-Payment Flows',
    source_sha256: '057c5bc174d455d6ab71be0a7a2ec07f945b1a7d303f94241b64b6dce211ccc1',
    native_binding: 'ABSENT',
    missing_material_fields: ['operation', 'target_ref', 'parameters_digest'],
    paths: p('/payment/action', '/payment/target', '/payment/parameters', '/receipt/audience'),
    evidence: ['Sections 5-6', 'The receipt binds compliance evidence and chain linkage but is not itself an exact-action authorization object.'],
    request: 'Please check whether the payment linkage contains a stable action commitment or should reference an external action identifier.',
  },
];
