// SPDX-License-Identifier: Apache-2.0
//
// Human-reviewed source data for the Consequential Action Interoperability
// Project. These are candidate mappings, not author endorsements.

const p = (operation, target, parameters) => ({
  operation,
  target,
  parameters,
});

export const targets = [
  {
    draft: 'draft-klrc-aiagent-auth',
    revision: '03',
    title: 'AI Agent Authentication and Authorization',
    source_sha256: '41b3899039a6c978c69eed32b17485a72f6dfef72c96d38eec9bbe9b0190e37a',
    native_binding: 'ABSENT',
    missing_material_fields: ['operation', 'target_ref', 'parameters_digest'],
    paths: p(null, null, null),
    evidence: ['Sections 9.2.2, 10.1, 10.3, 10.5, and 11, pages 12-16 and 20-21', 'Mission authorization translation is out of scope, and the audit discussion is prose rather than a defined exact-action wire object.'],
    request: 'Does this draft intend to define any native exact-action carrier, or should mappings remain absent and compose with separate request-binding profiles?',
  },
  {
    draft: 'draft-mcguinness-oauth-ai-agent-instance',
    revision: '00',
    title: 'OAuth 2.0 AI Agent Instance Profile',
    source_sha256: '347ae484d4c18d35d166281921bc7860b1ca4d9847db125d9fa917a7142fa476',
    native_binding: 'ABSENT',
    missing_material_fields: ['operation', 'target_ref', 'parameters_digest'],
    paths: p(null, null, null),
    excluded_native_candidates: [
      { source_path: '/scope', reason: 'Generic permission vocabulary, not a portable operation/target/parameter object.' },
      { source_path: '/aud', reason: 'Token audience is verifier context, not the concrete effect target.' },
    ],
    evidence: ['Sections 1, 4, 8, and 15.9, pages 4-5, 7-8, 12, and 20', 'The profile supplies agent-instance identity and provenance and explicitly composes with external permission mechanisms; it defines no exact-action object.'],
    request: 'Can you confirm this profile supplies actor identity and provenance only, so exact-action mappings must not parse scope or aud as target authority?',
  },
  {
    draft: 'draft-noa-scitt-ai-agent-receipt',
    revision: '00',
    title: 'A SCITT Profile for AI-Agent Action Receipts',
    source_sha256: '10e5d7ade5a7650348f85dac357c2db449d8329e2700ad0cf5ee8b3a1e0a921d',
    native_binding: 'PARTIAL',
    missing_material_fields: ['target_ref', 'parameters_digest'],
    paths: p('/action/id', null, null),
    path_kind: 'NATIVE_WIRE',
    missing_reasons: {
      target_ref: 'action.id names the tool or action and action.canonical is a risk-table key; neither identifies the concrete effect target.',
      parameters_digest: 'action.paramsHash is opaque and may be tenant-keyed HMAC; raw parameters and a profile-independent cross-producer parameter commitment are intentionally absent.',
    },
    excluded_native_candidates: [
      { source_path: '/action/canonical', reason: 'Risk-table key, not the executed operation or concrete target.' },
      { source_path: '/action/paramsHash', reason: 'Opaque SHA-256 or tenant-keyed HMAC without a profile-independent cross-producer parameter projection.' },
    ],
    evidence: ['Sections 3-4, pages 4-6', 'action.id identifies the tool/action; action.canonical is a risk-table key; paramsHash is hash-only and may use a tenant-scoped HMAC key.'],
    request: 'Please confirm this corrected reading: action.id can identify the operation class, while concrete target and profile-independent parameter commitment remain unavailable.',
  },
  {
    draft: 'draft-ietf-wimse-arch',
    revision: '08',
    title: 'Workload Identity in a Multi System Environment (WIMSE) Architecture',
    source_sha256: '5577c6a92d6f6b9ebf70d7da61365cf777277534ab0c3c2aa7f4698a1b4541f4',
    native_binding: 'ABSENT',
    missing_material_fields: ['operation', 'target_ref', 'parameters_digest'],
    paths: p(null, null, null),
    evidence: ['Sections 2, 3.3, 3.4.4-3.4.7, and 4.5, pages 4-5, 15-17, 23-25, and 30', 'The Security Context is abstract and message-level authorization formats and PEP/PDP protocol are out of scope; no native action schema exists.'],
    request: 'Should exact-action extraction be left to a concrete WIMSE protocol or Security Context profile, with this architecture correctly remaining absent?',
  },
  {
    draft: 'draft-ietf-wimse-http-signature',
    revision: '05',
    title: 'WIMSE Workload-to-Workload Authentication with HTTP Signatures',
    source_sha256: '96ae3e18caf3ce05229e4d789ffd3eff847cba7984710f86c85d5677113fadfc',
    native_binding: 'PARTIAL',
    missing_material_fields: ['parameters_digest'],
    paths: p('/signed_components/@method', '/signed_components/@request-target', null),
    path_kind: 'DETERMINISTIC_ADAPTER_OUTPUT',
    missing_reasons: {
      parameters_digest: 'A signed Content-Digest commits representation bytes, but the draft does not define a complete abstract action-parameter projection including every semantics-affecting component.',
    },
    excluded_native_candidates: [
      { source_path: '/signed_components/body', reason: 'Not a native field; the body is indirectly protected by a covered Content-Digest.' },
    ],
    evidence: ['Sections 3, 3.1, 5.2, and 6.3, pages 4-7, 12, and 14', 'The profile covers @method and @request-target and requires a signed Content-Digest for a body, but it does not define the complete semantic parameter projection.'],
    request: 'Which body, query, and semantics-affecting headers constitute the complete action parameters: is Content-Digest intended to suffice, or is a companion action profile required?',
  },
  {
    draft: 'draft-ietf-wimse-workload-creds',
    revision: '02',
    title: 'WIMSE Workload Credentials',
    source_sha256: 'b111e4e85a7f3bc5c844560db87276c184a04db28ffeaccb057c13eb034dbed5',
    native_binding: 'ABSENT',
    missing_material_fields: ['operation', 'target_ref', 'parameters_digest'],
    paths: p(null, null, null),
    evidence: ['Sections 1-1.3, 4, 5.1, and 7, pages 4-13 and 15', 'WIT and WIC establish workload identity and proof-of-possession context; protocol bindings and message authorization are external.'],
    request: 'Can you confirm WIT sub and the WIC URI SAN remain actor context and must not be projected as the consequential-action target?',
  },
  {
    draft: 'draft-ietf-wimse-wpt',
    revision: '01',
    title: 'WIMSE Workload Proof Token',
    source_sha256: 'a08af6270c8efd4a8320fb59e69bf29fe747ee14a4681be30aac9be45bf56e1e',
    native_binding: 'ABSENT',
    missing_material_fields: ['operation', 'target_ref', 'parameters_digest'],
    paths: p(null, null, null),
    excluded_native_candidates: [
      { source_path: '/aud', reason: 'WPT audience may be a deployment alias and is verifier context, not a concrete action target.' },
    ],
    evidence: ['Sections 2 and 3.3, pages 4-8 and 12', 'WPT carries audience, freshness, and token hashes but no method, query, body, or action-parameter commitment; major request portions remain unprotected.'],
    request: 'Given that method, query, and body are unbound and aud can be an alias, should exact-action equivalence require a companion request-binding profile?',
  },
  {
    draft: 'draft-bu-agentproto-security-principal-binding',
    revision: '03',
    title: 'Security Principal and Verifier Binding for Agent Communication Protocols',
    source_sha256: '52928b5e2384b981cdd69cb7178312eea588c5a63a18428bca8692a4d69e3f86',
    native_binding: 'ABSENT',
    missing_material_fields: ['operation', 'target_ref', 'parameters_digest'],
    paths: p(null, null, null),
    evidence: ['Sections 1-2, 6, 15, 18, 21, and 25, pages 3-7, 18-22, 27-29, and 33-34', 'The draft defines abstract claim classes, composition slots, and negative tests but deliberately defines no wire protocol or action object.'],
    request: 'Should every material CAID field remain unavailable until a candidate protocol mapping supplies a concrete carrier and byte-exact action construction?',
  },
  {
    draft: 'draft-rosomakho-oauth-txn-challenge',
    revision: '00',
    title: 'OAuth Transaction Authorization Challenge',
    source_sha256: 'a50c1fee4ce4ae486aa6e6739e9927586dc5c14a209434f44f76200354a8cead',
    native_binding: 'ABSENT',
    missing_material_fields: ['operation', 'target_ref', 'parameters_digest'],
    paths: p(null, null, null),
    excluded_native_candidates: [
      { source_path: '/authorization_details/0/type', reason: 'RAR detail type discriminator, not the requested operation.' },
      { source_path: '/iss', reason: 'Challenge issuer identifier, not the concrete action target.' },
    ],
    evidence: ['Sections 4.2.1-4.3, pages 9-12', 'The challenge carries a transaction identifier and profile-defined RAR details; the base draft does not define operation, concrete target, or complete parameters.'],
    request: 'Should exact-action extraction be defined only by each RAR detail profile, with the base transaction challenge remaining absent?',
  },
  {
    draft: 'draft-nelson-agent-delegation-receipts',
    revision: '10',
    title: 'Delegation Receipt Protocol for AI Agent Authorization',
    source_sha256: '08ba640802f461ed30e66f9b2cd7a50a3570b5838c39bf012c2b039ee2ed68bb',
    native_binding: 'PARTIAL',
    missing_material_fields: ['target_ref', 'parameters_digest'],
    paths: p('/scope/allowedActions/0/operation', null, null),
    path_kind: 'NATIVE_WIRE',
    excluded_native_candidates: [
      { source_path: '/scope/allowedActions/0/resource', reason: 'May be a resource class or wildcard and does not necessarily identify one concrete effect target.' },
      { source_path: '/boundaries', reason: 'Delegation prohibitions and limits, not a complete per-execution parameter set.' },
    ],
    evidence: ['Sections 4.1-6.4, pages 8-29', 'allowedActions binds operation scope, while resource may be a class or wildcard and boundaries constrain delegation rather than commit one execution.'],
    request: 'What per-execution artifact binds one concrete resource and complete parameters beneath the delegation receipt?',
  },
  {
    draft: 'draft-jiang-oauth-intent-admission',
    revision: '00',
    title: 'Intent Admission Assertions for Agentic Systems',
    source_sha256: 'd672a85cadaafccccf80489befa7018f6ffbdc749d361b1c8fe5d79468419867',
    native_binding: 'PARTIAL',
    missing_material_fields: ['target_ref', 'parameters_digest'],
    paths: p('/authorization_details/0/actions/0', null, null),
    path_kind: 'NATIVE_WIRE',
    excluded_native_candidates: [
      { source_path: '/authorization_details/0/locations/0', reason: 'RAR resource-location scope, not necessarily one concrete effect target.' },
      { source_path: '/authorization_details/0/constraints', reason: 'Optional authorization envelope constraints, not complete execution parameters.' },
      { source_path: '/intent_ref', reason: 'Digest of the whole intent object, not a separately compatible parameter digest.' },
    ],
    evidence: ['Sections 4.1-5, pages 8-10', 'The assertion binds admitted action scope and whole-intent evidence, but base RAR locations and constraints do not profile-independently identify one target and parameter set.'],
    request: 'Should a concrete RAR profile define the per-action target and parameter projection while the base assertion remains partial?',
  },
  {
    draft: 'draft-araut-oauth-transaction-tokens-for-agents',
    revision: '02',
    title: 'Transaction Tokens For Agents',
    source_sha256: 'c69ce45480dfbd46f6972770a2adb7d99396db5333f3438ecdd1b2a215bf3234',
    native_binding: 'ABSENT',
    missing_material_fields: ['operation', 'target_ref', 'parameters_digest'],
    paths: p(null, null, null),
    evidence: ['Transaction Token claims and multi-agent examples', 'The draft uses txn, sub, aud, scope, tctx, req_wl, and agentic_ctx but defines no /transaction object or profile-independent exact-action projection.'],
    request: 'Which concrete transaction-context profile, if any, defines operation, one target, and complete material parameters for exact-action comparison?',
  },
  {
    draft: 'draft-coetzee-oauth-spt-txn-tokens',
    revision: '03',
    title: 'Transaction-Bound Authorization Tokens for Software and AI Agents (SPT-Txn)',
    source_sha256: '5ebba0db429816a7fe887128f08d51c3840209bf17de74d66581ce935966e195',
    native_binding: 'COMPLETE',
    missing_material_fields: [],
    paths: p('/tool', '/target', '/params'),
    path_kind: 'DETERMINISTIC_ADAPTER_OUTPUT',
    excluded_native_candidates: [
      { source_path: '/spt_intent_digest', reason: 'Whole-intent token digest; it cannot be reused as the digest of parameters alone.' },
    ],
    evidence: ['Sections 3.1 and 5.1-5.3, pages 5-9', 'The token carries a whole-intent digest, while the normative verified preimage is the JCS object {tool, params, target}; the adapter maps that verified preimage rather than decomposing the digest.'],
    request: 'Please confirm that implementations retain or reconstruct the verified intent preimage so an exact-action adapter can map tool, target, and params without treating spt_intent_digest as a parameter digest.',
  },
  {
    draft: 'draft-mcguinness-oauth-actor-profile',
    revision: '00',
    title: 'OAuth Actor Profile for Delegation',
    source_sha256: 'd6b47ec71b32a6dcc9f22603925b95f3bce2b631041dcda0c8179eb6712c2dd9',
    native_binding: 'ABSENT',
    missing_material_fields: ['operation', 'target_ref', 'parameters_digest'],
    paths: p(null, null, null),
    evidence: ['Interoperability and permission-decision scope', 'The profile standardizes actor representation and propagation while leaving actor permissions and action semantics deployment-specific.'],
    request: 'Please check whether act-chain claims should remain authenticated actor context and reference a separate action object.',
  },
  {
    draft: 'draft-rampalli-cross-org-delegation-mapping',
    revision: '05',
    title: 'A Layered Requirements Mapping for Cross-Organization Agent Delegation',
    source_sha256: 'd1a8e0cd4cd59a8377a4949146a20c37457dab002e5d86bba343073798103bef',
    native_binding: 'ABSENT',
    missing_material_fields: ['operation', 'target_ref', 'parameters_digest'],
    paths: p(null, null, null),
    evidence: ['Sections 3-3.4, pages 8-13', 'The requirements model joins evidence by action digest but does not define the canonical action object that produced that digest.'],
    request: 'Please check whether the shared digest should carry a profile identifier so different canonicalizers cannot appear equivalent.',
  },
  {
    draft: 'draft-mih-scitt-agent-action-capsule-sel-disc',
    revision: '00',
    title: 'Selective Disclosure Profile for Agent Action Capsules',
    source_sha256: '7d06ae8ada91ca054336f200836755e15aec454c3fb5288d3d0457e6d8b1cd10',
    native_binding: 'PARTIAL',
    paths: p('/action_type', null, null),
    missing_material_fields: ['target_ref', 'parameters_digest'],
    path_kind: 'NATIVE_WIRE',
    excluded_native_candidates: [
      { source_path: '/effect/external_ref', reason: 'Outcome correlation reference, not the concrete requested-action target.' },
      { source_path: '/effect/request_digest', reason: 'Digest of the whole request, not a separately compatible parameter digest.' },
    ],
    evidence: ['Sections 4.4.3-4.4.6 and 5.2-5.4, pages 8-11', 'The capsule exposes action_type, while effect.external_ref is outcome correlation and effect.request_digest commits the whole request.'],
    request: 'Is effect.external_ref only outcome correlation and effect.request_digest explicitly whole-request; if so, what identifies the concrete target and complete parameters?',
  },
  {
    draft: 'draft-emirdag-scitt-ai-agent-execution',
    revision: '00',
    title: 'AI Agent Execution Profile of SCITT',
    source_sha256: '716a92dc5bb56e812aeaae5e3b7a7374c279957b4e88ad8eddc3c93695b2f836',
    native_binding: 'PARTIAL',
    paths: p('/action_type', null, null),
    missing_material_fields: ['target_ref', 'parameters_digest'],
    path_kind: 'NATIVE_WIRE',
    excluded_native_candidates: [
      { source_path: '/external_refs', reason: 'Optional generic cross-references, not a defined concrete action target.' },
      { source_path: '/input_hash', reason: 'Hash of raw agent input, not the complete material parameters of the consequential action.' },
      { source_path: '/content_hash', reason: 'Digest of the whole AIR payload, not an independently compatible parameter digest.' },
    ],
    evidence: ['Sections 5.2-5.3 and 5.5-5.7, pages 8-15', 'The AIR exposes action_type, but optional references, raw-input hashes, per-tool hashes, and whole-record hashes do not define target and complete parameters.'],
    request: 'Which AIR field identifies the exact affected resource, and what canonical byte domain commits the complete action parameters rather than raw input or the entire AIR?',
  },
  {
    draft: 'draft-lee-orprg-permit-receipts',
    revision: '00',
    title: 'Permit Receipts for Permit-Before-Commit Authorization of AI-Agent and Workload External Effects',
    source_sha256: 'ea164cf92f89490f8b9ad6c7accf0726f6b33cd72925c3bcc148cb7c65286bac',
    native_binding: 'ABSENT',
    missing_material_fields: ['operation', 'target_ref', 'parameters_digest'],
    paths: p(null, null, null),
    missing_reasons: {
      operation: 'The draft defines an effect-type-specific canonical request but no profile-independent operation member.',
      target_ref: 'scope.target_id is authorization scope and the canonical request structure is profile-defined; no universal concrete-target extraction is defined.',
      parameters_digest: 'action_digest commits to the entire canonical request, not a separately extractable parameter set or parameter digest.',
    },
    excluded_native_candidates: [
      { source_path: '/receipt_core/action_digest', reason: 'Digest of the full profile-selected canonical request; it cannot be decomposed into operation, target, and parameter commitments.' },
      { source_path: '/receipt_core/scope/target_id', reason: 'Authorization-scope field, not guaranteed to be the canonical request target.' },
    ],
    native_profile_role: 'Executable fail-closed probe. The reserved /__caid_unavailable__/* paths are deliberately absent from the fixture and are not fields defined by ORPRG revision -00.',
    evidence: [
      'Sections 2, 4 (REQ-2), 6-7, 9-11',
      'ORPRG binds the full canonical external-effect request through action_digest or action_commitment under an identified canonicalization profile. Revision -00 does not define a profile-independent decomposition into operation, target_ref, and parameters_digest; that projection requires a selected effect-specific profile and the verified canonical request.',
    ],
    request: 'Please check the canonical effect-request field projection and whether policy epoch belongs outside action identity.',
    author_review: {
      status: 'AUTHOR_FEEDBACK_RECORDED',
      confirmed_at: '2026-07-28',
      scope: 'Revision -00 and this narrow mapping disposition only; not validation of the CAID harness or broader interoperability pack, and not implementation, adoption, or endorsement.',
      finding: 'The profile-independent result remains PARTIAL to INDETERMINATE. Policy epoch and authorization audience remain verifier context outside material action identity, while a material effect recipient remains inside the selected action profile.',
    },
  },
  {
    draft: 'draft-baur-pap',
    revision: '02',
    title: 'Principal Agent Protocol (PAP)',
    source_sha256: 'a0c97214df66689f8fb6b7206e8abf1efcc94a309044cbfe114c889c0f6c4535',
    native_binding: 'PARTIAL',
    missing_material_fields: ['target_ref', 'parameters_digest'],
    paths: p('/action', null, null),
    path_kind: 'NATIVE_WIRE',
    missing_reasons: {
      target_ref: 'ScopeAction.object is a Schema.org object-class constraint and capability.target_did identifies the peer agent; neither is the concrete effect target.',
      parameters_digest: 'ScopeAction.conditions constrain delegated scope but do not commit to the complete parameters of one consequential execution.',
    },
    excluded_native_candidates: [
      { source_path: '/scope/actions/0/object', reason: 'Schema.org object class constraint, not a concrete target.' },
      { source_path: '/scope/actions/0/conditions', reason: 'Delegated-scope conditions, not a complete per-execution parameter set.' },
      { source_path: '/capability/target_did', reason: 'Receiving agent identity, not the target of the consequential effect.' },
    ],
    evidence: ['Sections 5.4.2 and 6.2, pages 15 and 22-23', 'PAP defines action and object classes plus a single-use session capability; it does not bind the concrete effect target or complete per-execution parameters.'],
    request: 'Please confirm that PAP authorizes a session/action class and that a per-execution adapter is still needed to bind the concrete target and complete parameters.',
  },
  {
    draft: 'draft-pidlisnyi-aps',
    revision: '03',
    title: 'Agent Passport System (APS): Verifiable Agent Identity, Faceted Authority, and Signed Action Receipts',
    source_sha256: '59b9547a20c6d514eceb97d169b92b2f9c70a231f5b914e8fc1b478c7f359fca',
    native_binding: 'COMPLETE',
    missing_material_fields: [],
    paths: p('/action_ref/action_type', '/action_ref/target', '/action_ref/payload_ref'),
    path_kinds: {
      operation: 'NATIVE_WIRE',
      target_ref: 'NATIVE_WIRE',
      parameters_digest: 'NATIVE_WIRE',
    },
    transforms: {
      parameters_digest: 'sha256-hex-to-digest',
    },
    native_fixture_fields: {
      '/action_ref/profile': 'aps-action-ref-v2',
      '/action_ref/agent_id': 'did:key:z6MkExampleAgent',
      '/action_ref/scope_required': ['medical:coverage'],
      '/action_ref/issued_at': '2026-04-08T12:00:00.000Z',
      '/action_ref/nonce': '00112233445566778899aabbccddeeff',
    },
    omitted_source_fields: [
      { source_path: '/action_ref/profile', reason: 'APS commits the native ActionRefV2 profile tag; the local CAID action does not carry that source identifier field.' },
      { source_path: '/action_ref/agent_id', reason: 'APS deliberately makes the acting agent part of action_ref; CAID keeps actor identity outside material action identity.' },
      { source_path: '/action_ref/scope_required', reason: 'APS commits required authority scopes; CAID keeps authorization scope outside material action identity.' },
      { source_path: '/action_ref/issued_at', reason: 'APS commits intent issuance time; CAID keeps freshness outside material action identity.' },
      { source_path: '/action_ref/nonce', reason: 'APS commits a replay-resistant nonce; CAID keeps replay state outside material action identity.' },
    ],
    excluded_native_candidates: [
      { source_path: '/action_ref', reason: 'Receipt field is a scalar digest of ActionRefV2, not the decomposed action.' },
    ],
    evidence: ['Section 4.1, pages 14-15', 'ActionRefV2 contains exactly profile, agent_id, action_type, target, payload_ref, scope_required, issued_at, and nonce; payload_ref is a domain-separated SHA-256 commitment and the native action identity deliberately includes actor, authority, freshness, and replay context.'],
    request: 'Please confirm this declared-loss result: action_type, target, and payload_ref correlate to CAID content, while profile, agent_id, scope_required, issued_at, and nonce remain authenticated APS context and prevent identifier equivalence.',
  },
  {
    draft: 'draft-howe-vcon-agent-session',
    revision: '00',
    title: 'vCon Agent Session',
    source_sha256: 'b88e60f74fc6737ceb4ffd230c2bfa49b5c5250b64b058bcd009b4b75a61c507',
    native_binding: 'ABSENT',
    missing_material_fields: ['operation', 'target_ref', 'parameters_digest'],
    paths: p(null, null, null),
    excluded_native_candidates: [
      { source_path: '/tool_call', reason: 'No such native object is defined by this pinned draft; tool-call semantics are delegated to an unversioned VAC body schema.' },
    ],
    evidence: ['Sections 3, 6.1-6.3, 7, and 13.1, pages 4, 7-9, and 11', 'The draft defines a vCon analysis wrapper and delegates action structure to an unversioned VAC schema, so no stable exact-action extraction is pinned.'],
    request: 'Which exact VAC revision or schema URL is mandatory, and what stable VAC fields identify operation, concrete target, and complete arguments?',
  },
  {
    draft: 'draft-pei-opsawg-agentops-observability',
    revision: '00',
    title: 'AgentOps Observability for Failure Detection and Attribution',
    source_sha256: '00a060440ced78e138ac89a7ba65ad083880569febf78586dd937ade42c9e35c',
    native_binding: 'PARTIAL',
    missing_material_fields: ['target_ref', 'parameters_digest'],
    paths: p('/action/kind', null, null),
    path_kind: 'NATIVE_WIRE',
    excluded_native_candidates: [
      { source_path: '/action/input_ref/hash', reason: 'Optional hash with no mandated algorithm, preimage domain, or complete-input rule.' },
    ],
    evidence: ['Sections 4.1-4.5, pages 6-10', 'The event exposes action.kind, but no resource target; optional input_ref.hash lacks an algorithm-pinned complete material-input definition.'],
    request: 'Is action.kind intended as the exact operation, and where are the affected resource and a mandatory digest of complete material input defined?',
  },
  {
    draft: 'draft-dunbar-dmsc-gw-scenarios-gap-analysis',
    revision: '02',
    title: 'Deployment Scenarios and Gap Analysis for AI Agent Gateway',
    source_sha256: '17ebf5da730d45266e51052ee806d7d824539348ca89d362a7784e3d50d7c499',
    native_binding: 'ABSENT',
    missing_material_fields: ['operation', 'target_ref', 'parameters_digest'],
    paths: p(null, null, null),
    evidence: ['Sections 6.7, 6.9, 7.5, and 7.7, pages 25-31', 'The document identifies cross-gateway action authorization and physical-action coordination as standardization gaps but defines no wire object.'],
    request: 'For the gaps in Sections 6.7 and 6.9, will companion work define a closed cross-gateway physical-action object with operation, canonical target, and complete parameter commitment, or is this document intentionally gap-only?',
  },
  {
    draft: 'draft-soden-wellknown-mcp-commerce',
    revision: '00',
    title: 'A Well-Known URI Profile for Agent-Callable Commerce Endpoints',
    source_sha256: 'd6e8a6119fe2797490afb6a4106ee57834ac1ac4761abe149d7666deb994a917',
    native_binding: 'ABSENT',
    missing_material_fields: ['operation', 'target_ref', 'parameters_digest'],
    paths: p(null, null, null),
    excluded_native_candidates: [
      { source_path: '/_meta/com.beaconspec~1commerce/endpoint/url', reason: 'Discovery server URL, not the concrete target of a selected consequential transaction.' },
    ],
    evidence: ['Sections 2.1, 3.5, 3.11, 4, and 5, pages 5-10', 'The profile advertises a commerce server endpoint and capability inventory but defines no selected operation, transaction target, or invocation parameters.'],
    request: 'Will a future profile bind one selected capability invocation to a concrete transaction target and parameter digest rather than only advertise an endpoint?',
  },
  {
    draft: 'draft-hopley-x402-compliance-receipt',
    revision: '02',
    title: 'Categorical Compliance Screening Receipt Format for Agentic-Payment Flows',
    source_sha256: '057c5bc174d455d6ab71be0a7a2ec07f945b1a7d303f94241b64b6dce211ccc1',
    native_binding: 'ABSENT',
    missing_material_fields: ['operation', 'target_ref', 'parameters_digest'],
    paths: p(null, null, null),
    excluded_native_candidates: [
      { source_path: '/payer_ref', reason: 'Payer actor identity reference, not the payment or consequential-action target.' },
      { source_path: '/content_hash', reason: 'Digest of the whole receipt, not an action or parameter commitment.' },
    ],
    evidence: ['Sections 3-5, pages 6-10', 'The receipt covers payer identity, categorical screening result, time, provider, jurisdictions, and canonicalization, but no payment ID, payee, amount, operation, or parameters.'],
    request: 'What payment, mandate, or action reference scopes an ALLOW receipt to one transaction and prevents replay across different payments?',
  },
];
