#!/usr/bin/env node
// SPDX-License-Identifier: Apache-2.0
/**
 * Deterministically regenerates the synthetic Claim Assurance reference case.
 *
 *   node examples/claim-assurance-reference/generate.mjs --check
 *   node examples/claim-assurance-reference/generate.mjs --print
 *   node examples/claim-assurance-reference/generate.mjs --write
 *
 * `--check` performs the complete offline replay: it hashes the independently
 * supplied verifier source, pins that implementation and the profile, evaluates
 * the Claim Case, and compares every generated byte with the committed files.
 */

import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  CLAIM_ASSURANCE_PROFILE_VERSION,
  CLAIM_CASE_VERSION,
  claimAssuranceArtifactDigest,
  claimAssuranceProfileHash,
  evaluateClaimAssurance,
  inspectAssuranceRecordIntegrity,
} from '../../packages/verify/claim-assurance.js';
import {
  REFERENCE_VERIFIER_ID,
  REFERENCE_VERIFIER_VERSION,
  createReferenceVerifierRegistration,
} from './reference-verifier.mjs';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, '../..');
const VERIFIER_PATH = path.join(HERE, 'reference-verifier.mjs');
const AS_OF = '2026-08-23T12:00:00Z';
const EVALUATED_AT = '2026-08-23T12:00:01Z';

/** @returns {import('../../packages/verify/dist/claim-assurance.js').Sha256Digest} */
function sha256Bytes(bytes) {
  return `sha256:${crypto.createHash('sha256').update(bytes).digest('hex')}`;
}

/** @returns {import('../../packages/verify/dist/claim-assurance.js').Sha256Digest} */
function sha256Text(value) {
  return sha256Bytes(Buffer.from(value, 'utf8'));
}

function jsonBytes(value) {
  return `${JSON.stringify(value, null, 2)}\n`;
}

function buildReference() {
  const implementationDigest = sha256Bytes(fs.readFileSync(VERIFIER_PATH));
  const verifier = {
    verifier_id: REFERENCE_VERIFIER_ID,
    verifier_version: REFERENCE_VERIFIER_VERSION,
    implementation_digest: implementationDigest,
  };
  const subjectDigest = sha256Text('EMILIA-SYNTHETIC-SUBJECT-v1\0fictional-vendor-aurora-supply');
  const scopeDigest = sha256Text('EMILIA-SYNTHETIC-SCOPE-v1\0fictional-company-ap-policy');
  const destinationDigest = claimAssuranceArtifactDigest({
    synthetic_reference_only: true,
    routing_number: '000000000',
    account_token: 'fictional-account-ending-4242',
  });
  const action = {
    '@type': 'EMILIA-SYNTHETIC-ACTION-v1',
    synthetic_reference_only: true,
    action_type: 'finance.vendor-payment-destination.change',
    vendor_ref: 'fictional-vendor-aurora-supply',
    proposed_destination_digest: destinationDigest,
  };
  const actionDigest = claimAssuranceArtifactDigest(action);
  const claimId = 'claim:synthetic:vendor-destination:aurora';
  /** @type {import('../../packages/verify/dist/claim-assurance.js').ClaimAssuranceProfile} */
  const profile = {
    '@type': CLAIM_ASSURANCE_PROFILE_VERSION,
    profile_id: 'emilia.reference.synthetic-vendor-destination.v1',
    claim_type: 'finance.vendor-payment-destination',
    predicate: 'proposed-destination-is-approved',
    requirements: [{
      requirement_id: 'two-synthetic-destination-observations',
      evidence_role: 'DESTINATION_OBSERVATION',
      verifier,
      minimum_distinct_sources: 2,
      max_age_seconds: 3_600,
    }],
  };
  const profileHash = claimAssuranceProfileHash(profile);
  const evidenceArtifacts = [
    {
      '@type': 'EMILIA-SYNTHETIC-DESTINATION-EVIDENCE-v1',
      synthetic_reference_only: true,
      source_id: 'synthetic:erp-vendor-master',
      subject_digest: subjectDigest,
      scope_digest: scopeDigest,
      claim_id: claimId,
      action_digest: actionDigest,
      observed_destination_digest: destinationDigest,
      observed_at: '2026-08-23T11:50:00Z',
      expires_at: '2026-08-24T11:50:00Z',
    },
    {
      '@type': 'EMILIA-SYNTHETIC-DESTINATION-EVIDENCE-v1',
      synthetic_reference_only: true,
      source_id: 'synthetic:out-of-band-callback-log',
      subject_digest: subjectDigest,
      scope_digest: scopeDigest,
      claim_id: claimId,
      action_digest: actionDigest,
      observed_destination_digest: destinationDigest,
      observed_at: '2026-08-23T11:55:00Z',
      expires_at: '2026-08-24T11:55:00Z',
    },
  ];
  const claimCase = {
    '@type': CLAIM_CASE_VERSION,
    subject_digest: subjectDigest,
    scope_digest: scopeDigest,
    claim: {
      claim_id: claimId,
      claim_type: profile.claim_type,
      predicate: profile.predicate,
      value: {
        synthetic_reference_only: true,
        destination_digest: destinationDigest,
      },
    },
    profile_id: profile.profile_id,
    profile_hash: profileHash,
    action_digest: actionDigest,
    as_of: AS_OF,
    evidence: evidenceArtifacts.map((artifact, index) => ({
      evidence_id: `evidence:synthetic:${index + 1}`,
      role: 'DESTINATION_OBSERVATION',
      verifier,
      binding: {
        subject_digest: subjectDigest,
        scope_digest: scopeDigest,
        claim_id: claimId,
        action_digest: actionDigest,
      },
      artifact,
      artifact_digest: claimAssuranceArtifactDigest(artifact),
    })),
  };
  const verifierRegistration = /** @type {import('../../packages/verify/dist/claim-assurance.js').EvidenceVerifierRegistration} */ (
    createReferenceVerifierRegistration(implementationDigest)
  );
  const record = evaluateClaimAssurance(claimCase, {
    pinned_profile: profile,
    pinned_profile_hash: profileHash,
    verifier_registry: [verifierRegistration],
    evaluated_at: EVALUATED_AT,
    expected_action_digest: actionDigest,
  });
  const integrity = inspectAssuranceRecordIntegrity(record, {
    expected_record_digest: record.record_digest,
  });
  if (!integrity.integrity_valid || record.verdict !== 'VERIFIED' || record.authorizes_action !== false) {
    throw new Error('synthetic reference record did not satisfy its safety invariants');
  }

  const publicPath = path.join(
    ROOT,
    'public/assurance/records',
    `${record.record_digest.replace(':', '-')}.json`,
  );
  return {
    record_id: record.record_digest,
    files: new Map([
      [path.join(HERE, 'profile.json'), jsonBytes(profile)],
      [path.join(HERE, 'claim-case.json'), jsonBytes(claimCase)],
      [publicPath, jsonBytes(record)],
    ]),
  };
}

function relative(file) {
  return path.relative(ROOT, file);
}

function check(reference) {
  const drift = [];
  for (const [file, expected] of reference.files) {
    if (!fs.existsSync(file)) {
      drift.push(`${relative(file)} is missing`);
      continue;
    }
    if (fs.readFileSync(file, 'utf8') !== expected) drift.push(`${relative(file)} has drifted`);
  }
  if (drift.length > 0) {
    throw new Error(`claim assurance reference check failed:\n${drift.map((line) => `- ${line}`).join('\n')}`);
  }
  process.stdout.write(`Claim Assurance reference verified offline: ${reference.record_id}\n`);
}

function write(reference) {
  for (const [file, contents] of reference.files) {
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, contents, 'utf8');
    process.stdout.write(`wrote ${relative(file)}\n`);
  }
  process.stdout.write(`record_id=${reference.record_id}\n`);
}

function print(reference) {
  const output = { record_id: reference.record_id, files: {} };
  for (const [file, contents] of reference.files) output.files[relative(file)] = JSON.parse(contents);
  process.stdout.write(`${JSON.stringify(output, null, 2)}\n`);
}

const mode = process.argv[2] ?? '--check';
const reference = buildReference();
if (mode === '--check') check(reference);
else if (mode === '--write') write(reference);
else if (mode === '--print') print(reference);
else throw new Error('usage: generate.mjs [--check|--write|--print]');
