// SPDX-License-Identifier: Apache-2.0
//
// Regression guard for scripts/build-standalone-runtimes.mjs: the ./src ->
// ./dist import rewrite applied to package test companions used to live only
// on the SPDX-anchored return path, so a .test.ts whose header was a JSDoc
// @license block (or anything else that is not the exact SPDX line comment)
// fell through to a branch that returned the raw transpiler output and
// silently shipped a companion importing ./src, which `node --test` on
// Node 20 cannot resolve.
import { mkdtemp, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { afterAll, beforeAll, describe, expect, it } from 'vitest';

// @ts-expect-error -- plain .mjs build script, no type declarations.
import { renderRuntime } from '../scripts/build-standalone-runtimes.mjs';

const BANNER = '// Generated by test. Do not edit.\n/* eslint-disable */\n';

let scratch: string;

async function render(relativeSource: string, source: string): Promise<string> {
  const sourcePath = join(scratch, relativeSource.replaceAll('/', '__'));
  await writeFile(sourcePath, source, 'utf8');
  return renderRuntime({ relativeSource, sourcePath, banner: BANNER });
}

const SPDX_HEADER = '// SPDX-License-Identifier: Apache-2.0\n';
const JSDOC_HEADER = '/**\n * @license Apache-2.0\n */\n';
const BODY = "import { verifyReceipt } from './src/index.ts';\n\nexport const probe = verifyReceipt;\n";

beforeAll(async () => {
  scratch = await mkdtemp(join(tmpdir(), 'standalone-runtime-rewrite-'));
});

afterAll(async () => {
  await rm(scratch, { recursive: true, force: true });
});

describe('standalone runtime companion ./src -> ./dist rewrite', () => {
  it('rewrites on the SPDX-anchored path', async () => {
    const out = await render('packages/verify/spdx.test.ts', `${SPDX_HEADER}${BODY}`);
    expect(out).toContain("from './dist/index.ts'");
    expect(out).not.toContain("from './src/");
  });

  it('rewrites when the header is a JSDoc @license block, not an SPDX line', async () => {
    const out = await render('packages/verify/jsdoc.test.ts', `${JSDOC_HEADER}${BODY}`);
    expect(out).toContain("from './dist/index.ts'");
    expect(out).not.toContain("from './src/");
  });

  it('rewrites when a shebang precedes a JSDoc header', async () => {
    const out = await render(
      'packages/gate/shebang.test.mts',
      `#!/usr/bin/env node\n${JSDOC_HEADER}${BODY}`,
    );
    expect(out.startsWith('#!/usr/bin/env node\n')).toBe(true);
    expect(out).toContain("from './dist/index.ts'");
    expect(out).not.toContain("from './src/");
  });

  it('keeps the generated banner on every path', async () => {
    for (const [relativeSource, source] of [
      ['packages/verify/banner-spdx.test.ts', `${SPDX_HEADER}${BODY}`],
      ['packages/verify/banner-jsdoc.test.ts', `${JSDOC_HEADER}${BODY}`],
      ['packages/gate/banner-shebang.test.mts', `#!/usr/bin/env node\n${JSDOC_HEADER}${BODY}`],
    ] as const) {
      expect(await render(relativeSource, source), relativeSource).toContain(BANNER.trimEnd());
    }
  });

  it('leaves non-test package sources alone', async () => {
    const out = await render('packages/verify/src/index.ts', `${JSDOC_HEADER}${BODY}`);
    expect(out).toContain("from './src/index.ts'");
  });

  it('fails loudly, naming the file, when a package test companion still imports ./src', async () => {
    await expect(render('packages/scan/unmapped.test.ts', `${JSDOC_HEADER}${BODY}`))
      .rejects.toThrow(/packages\/scan\/unmapped\.test\.ts.*still imports \.\/src/s);
  });
});
