// SPDX-License-Identifier: Apache-2.0

// Package epgoconformance runs the EP hybrid post-quantum VERIFICATION
// conformance vectors against the Go verifier
// (github.com/emiliaprotocol/emilia-protocol/packages/go-verify/v2) with a
// LIVE ML-DSA-65 backend.
//
// WHY THIS IS A SEPARATE MODULE. packages/go-verify promises "Zero-dependency
// ... Standard library only" in its README, ships without a go.sum, and its
// release chain diffs the checked-out tree against the bytes the Go module
// proxy serves. Go's standard library has no exported ML-DSA-65 (only the
// unexported crypto/internal/fips140/mldsa), so a live post-quantum leg needs
// a third-party implementation. Putting that implementation here keeps the
// published verifier's dependency posture intact while still proving the PQ
// leg end to end against the checked-in vectors.
//
// BACKEND: github.com/cloudflare/circl/sign/mldsa/mldsa65, a FIPS 204 ML-DSA
// implementation. The checked-in vectors were generated by @noble/post-quantum
// (pure JavaScript). Neither implementation is FIPS validated and neither has
// completed an independent audit; that CIRCL verifies noble's signature bytes
// and rejects the tampered ones is cross-implementation agreement on the FIPS
// 204 encoding, not a certification claim.
package epgoconformance

import (
	"github.com/cloudflare/circl/sign/mldsa/mldsa65"

	emiliaverify "github.com/emiliaprotocol/emilia-protocol/packages/go-verify/v2"
)

// Backend implements emiliaverify.MldsaBackend over CIRCL's ML-DSA-65.
type Backend struct{}

// Assert the contract at compile time.
var _ emiliaverify.MldsaBackend = Backend{}

// Verify reports whether signature is a valid FIPS 204 ML-DSA-65 signature by
// publicKey over message, with an EMPTY context string (which is what
// @noble/post-quantum's ml_dsa65.verify signs and checks, and therefore what
// the checked-in vectors encode).
//
// It length-checks before unpacking and recovers from any panic, so malformed
// attacker-supplied bytes are a false, never a crash. That is the
// emiliaverify.MldsaBackend contract and it is what "fail-closed" requires of
// the PQ leg.
func (Backend) Verify(signature, message, publicKey []byte) (ok bool) {
	if len(publicKey) != mldsa65.PublicKeySize || len(signature) != mldsa65.SignatureSize {
		return false
	}
	defer func() {
		if recover() != nil {
			ok = false
		}
	}()
	var packed [mldsa65.PublicKeySize]byte
	copy(packed[:], publicKey)
	var pk mldsa65.PublicKey
	pk.Unpack(&packed)
	return mldsa65.Verify(&pk, message, nil, signature)
}
