'use client';

/**
 * ProofBlock — the formal-verification trust anchor.
 * @license Apache-2.0
 *
 * The spear tip: almost nobody in AI governance can say "we machine-checked our
 * safety properties." EP can. Copy is ground-truthed against formal/ep_handshake.tla
 * + ep_relations.als; the counts (TLA+ invariants, Alloy facts, Alloy assertions)
 * are read live from lib/proof-stats.json so they can never drift, Alloy 6.0.0,
 * checked in CI. Invariant identifiers below are the REAL source names — do not
 * invent friendly labels.
 */

import Link from 'next/link';
import { motion } from 'motion/react';
import { color, font, radius } from '@/lib/tokens';
import proofStats from '@/lib/proof-stats.json';

const EASE = [0.23, 1, 0.32, 1];

// Numbers are ground-truthed to lib/proof-stats.json (regenerated by
// scripts/generate-proof-stats.mjs) so they can never drift from the formal
// models — same convention as app/page.js.
const TLA_INVARIANTS = String(proofStats.tla?.invariants ?? 26);
const ALLOY_FACTS = String(proofStats.alloy?.facts ?? 35);
const ALLOY_ASSERTIONS = String(proofStats.alloy?.assertions ?? 32);
const TAMARIN_OBLIGATIONS = String(proofStats.tamarin?.verifiedObligations ?? 0);
const TAMARIN_ATTACK_TRACES = String(proofStats.tamarin?.deliberatelyUnsafeCounterexamples ?? 0);
const SECURITY_CLAIMS = String(proofStats.securityCase?.claims ?? 0);
const EVIDENCE_FILES = String(proofStats.securityCase?.evidenceFiles ?? 0);
const TEST_CASES = Number(proofStats.tests?.total ?? 0).toLocaleString('en-US');
const CONFORMANCE_VECTORS = String(proofStats.conformance?.vectors ?? 0);

const STATS = [
  { n: TAMARIN_OBLIGATIONS, label: 'verified Tamarin lemmas' },
  { n: TAMARIN_ATTACK_TRACES, label: 'deliberately weakened attack traces' },
  { n: SECURITY_CLAIMS, label: 'executable security claims' },
  { n: EVIDENCE_FILES, label: 'hashed evidence files' },
];

// These are the exact lemma identifiers in ep_reliance_composed.spthy.
const TAMARIN_LEMMAS = [
  ['execution_requires_full_composition', 'Execution requires challenge, exact action, approvals, pinned authority, revocation, and consumption to compose.'],
  ['no_issuer_laundering', 'A presenter cannot turn its own key into an accepted issuer by relabeling the artifact.'],
  ['no_cross_action_profile_or_audience_replay', 'Valid evidence cannot be transplanted to another action, profile, or relying party.'],
  ['initiator_cannot_self_approve', 'The actor initiating an action cannot fill the human-approval seat.'],
  ['strict_registry_view_is_exact', 'Authority evidence must match the exact registry checkpoint pinned by the relying party.'],
  ['injective_execution_with_consumption', 'One consumed authorization maps to at most one checked execution.'],
];

const ATTACK_TRACES = [
  ['unchecked_composition_is_injective', 'Remove one-time consumption and Tamarin finds a same-receipt replay.'],
  ['unchecked_registry_view_is_current', 'Remove exact registry-view binding and Tamarin accepts a stale or equivocating authority view.'],
];

export default function ProofBlock() {
  const reveal = {
    initial: { opacity: 1, y: 18 },
    whileInView: { y: 0 },
    viewport: { once: true, margin: '-40px' },
    transition: { duration: 0.55, ease: EASE },
  };
  return (
    <motion.div {...reveal}>
      <div style={{ maxWidth: 900 }}>
        <div
          style={{
            fontFamily: font.mono,
            fontSize: 10,
            letterSpacing: 2,
            textTransform: 'uppercase',
            color: color.gold,
            marginBottom: 16,
          }}
        >
          Why this is different
        </div>
        <h2 style={{ fontFamily: font.sans, fontSize: 'clamp(30px,4.4vw,52px)', fontWeight: 700, letterSpacing: 0, lineHeight: 1.08, margin: '0 0 18px', color: color.t1 }}>
          Anyone can copy a schema. They cannot copy a security case by changing the logo.
        </h2>
        <p style={{ fontFamily: font.sans, fontSize: 18, lineHeight: 1.65, color: color.t2, maxWidth: 760, margin: 0 }}>
          EMILIA’s differentiation is not proprietary cryptography. It is a composed, machine-rerunnable
          argument that the whole path holds together: challenge, canonical action, human ceremony,
          issuer and authority pins, revocation, one-time consumption, and execution.
        </p>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, minmax(0, 1fr))', borderTop: `1px solid ${color.border}`, borderBottom: `1px solid ${color.border}`, marginTop: 48 }} className="ep-proof-stat-grid">
        {STATS.map((s, index) => (
          <div key={s.label} style={{ padding: '24px 20px', borderLeft: index === 0 ? 'none' : `1px solid ${color.border}` }}>
            <div style={{ fontFamily: font.mono, fontSize: 30, fontWeight: 700, color: color.gold }}>{s.n}</div>
            <div style={{ fontFamily: font.mono, fontSize: 10.5, color: color.t3, lineHeight: 1.45, marginTop: 5 }}>{s.label}</div>
          </div>
        ))}
      </div>

      <div className="ep-proof-composition-grid" style={{ display: 'grid', gridTemplateColumns: '4fr 8fr', gap: 44, padding: '56px 0' }}>
        <div>
          <div style={{ fontFamily: font.mono, fontSize: 10, letterSpacing: 2, textTransform: 'uppercase', color: color.gold, marginBottom: 14 }}>The composed path</div>
          <div style={{ fontFamily: font.mono, fontSize: 13, color: color.t1, lineHeight: 1.9 }}>
            challenge<br />↓ canonical action<br />↓ human ceremony<br />↓ issuer + authority<br />↓ revocation<br />↓ consumption<br />↓ execution
          </div>
          <p style={{ fontFamily: font.sans, fontSize: 14, color: color.t2, lineHeight: 1.65, margin: '20px 0 0' }}>
            Tamarin tests this as one symbolic protocol under a Dolev-Yao attacker with full network control,
            rather than assuming separately checked pieces compose safely.
          </p>
        </div>

        <div className="ep-proof-composition-detail" style={{ borderLeft: `1px solid ${color.border}`, paddingLeft: 44 }}>
          <div style={{ fontFamily: font.mono, fontSize: 10, letterSpacing: 2, textTransform: 'uppercase', color: color.t3, marginBottom: 4 }}>Named Tamarin lemmas</div>
          <div>
            {TAMARIN_LEMMAS.map(([name, plain]) => (
              <div key={name} style={{ padding: '16px 0', borderBottom: `1px solid ${color.border}` }}>
                <div style={{ display: 'flex', alignItems: 'baseline', justifyContent: 'space-between', gap: 16, flexWrap: 'wrap' }}>
                  <code style={{ fontFamily: font.mono, fontSize: 11.5, color: color.t1, overflowWrap: 'anywhere' }}>{name}</code>
                  <span style={{ fontFamily: font.mono, fontSize: 9, letterSpacing: 1.2, color: '#39734D' }}>VERIFIED · ALL TRACES</span>
                </div>
                <p style={{ fontFamily: font.sans, fontSize: 14, color: color.t2, lineHeight: 1.58, margin: '7px 0 0' }}>{plain}</p>
              </div>
            ))}
          </div>
        </div>
      </div>

      <div className="ep-proof-counterexample-band" style={{ background: '#1C1917', color: '#FAFAF9', borderRadius: radius.base, padding: '34px 36px' }}>
        <div style={{ fontFamily: font.mono, fontSize: 10, letterSpacing: 2, textTransform: 'uppercase', color: '#E6C97A', marginBottom: 12 }}>The model is allowed to prove us wrong</div>
        <h3 style={{ fontFamily: font.sans, fontSize: 23, lineHeight: 1.25, letterSpacing: 0, margin: 0, color: '#FAFAF9' }}>
          We deliberately remove controls and ask Tamarin to find the failure.
        </h3>
        <div className="ep-proof-trace-grid" style={{ display: 'grid', gridTemplateColumns: 'repeat(2, minmax(0, 1fr))', gap: 32, marginTop: 26 }}>
          {ATTACK_TRACES.map(([name, plain]) => (
            <div key={name} style={{ borderTop: '1px solid rgba(250,250,249,0.2)', paddingTop: 16 }}>
              <code style={{ fontFamily: font.mono, fontSize: 11, color: '#E6C97A', overflowWrap: 'anywhere' }}>{name}</code>
              <div style={{ fontFamily: font.mono, fontSize: 9, letterSpacing: 1.2, color: '#FCA5A5', marginTop: 7 }}>FALSIFIED · CONCRETE TRACE FOUND</div>
              <p style={{ fontFamily: font.sans, fontSize: 14, color: 'rgba(250,250,249,0.72)', lineHeight: 1.6, margin: '9px 0 0' }}>{plain}</p>
            </div>
          ))}
        </div>
      </div>

      <div className="ep-proof-advantage-grid" style={{ display: 'grid', gridTemplateColumns: '4fr 8fr', gap: 44, padding: '56px 0 0', marginTop: 8 }}>
        <div>
          <div style={{ fontFamily: font.mono, fontSize: 10, letterSpacing: 2, textTransform: 'uppercase', color: color.gold, marginBottom: 14 }}>What compounds</div>
          <h3 style={{ fontFamily: font.sans, fontSize: 26, lineHeight: 1.2, letterSpacing: 0, color: color.t1, margin: 0 }}>Open does not mean interchangeable.</h3>
        </div>
        <div>
          <p style={{ fontFamily: font.sans, fontSize: 16, color: color.t2, lineHeight: 1.7, margin: 0 }}>
            Nothing prevents another team from implementing the open format. That is the distribution
            strategy. But a compatible envelope is not an equivalent system. Equivalence means reproducing
            the composed proof, strict verifier behavior, negative vectors, durable consumption, release
            evidence, and every assumption and exclusion. Each discovered failure becomes a permanent,
            machine-rerunnable obligation. That body of evidence compounds with every release.
          </p>
          <p style={{ fontFamily: font.mono, fontSize: 11.5, color: color.t3, lineHeight: 1.7, margin: '20px 0 0' }}>
            Broader executable evidence: {TLA_INVARIANTS} TLA+ invariants · {ALLOY_FACTS} Alloy facts + {ALLOY_ASSERTIONS} assertions · {TEST_CASES} automated cases · {CONFORMANCE_VECTORS} current conformance vectors.
          </p>
        </div>
      </div>

      <p style={{ fontFamily: font.mono, fontSize: 11.5, color: color.t3, marginTop: 34, paddingTop: 22, borderTop: `1px solid ${color.border}`, lineHeight: 1.65 }}>
        Scope remains explicit: TLA+ and Alloy model bounded state and relational properties; Tamarin uses
        symbolic perfect cryptography and pinned-root assumptions. These are not proofs of AI behavior,
        WebAuthn internals, parser correctness, legal compliance, or deployment completeness.
      </p>

      <div style={{ display: 'flex', gap: 18, marginTop: 18, flexWrap: 'wrap' }}>
        <Link href="/proof" style={{ fontFamily: font.sans, fontSize: 14, fontWeight: 600, color: color.t1 }}>
          Inspect the engineering evidence →
        </Link>
        <Link href="/spec" style={{ fontFamily: font.sans, fontSize: 14, fontWeight: 600, color: color.t1 }}>
          Read the spec →
        </Link>
        <Link href="/blog/how-formal-verification-works-for-protocols" style={{ fontFamily: font.sans, fontSize: 14, fontWeight: 600, color: color.t1 }}>
          How the verification works →
        </Link>
      </div>
    </motion.div>
  );
}
