# Code generated by caid/spec/gen.mjs; DO NOT EDIT.
# Derived from caid/spec/caid.abnf, caid/spec/core.json, caid/registry/suites.json.
# The draft is the normative text; these constants are generated from it.
# Regenerate with: node caid/spec/gen.mjs --write

import re
import types


def _freeze(value):
    if isinstance(value, dict):
        return types.MappingProxyType({k: _freeze(v) for k, v in value.items()})
    if isinstance(value, (list, tuple)):
        return tuple(_freeze(v) for v in value)
    return value


# Rule data, read-only (mappings are MappingProxyType, sequences are tuples).
SPEC = _freeze({
    "draft": "draft-schrock-canonical-action-identifier-04",
    "identifier": {
        "scheme": "caid",
        "version": "1",
        "separator": ":",
        "parts": 5,
    },
    "patterns": {
        "caid": "caid\\x3a1\\x3a(?:[a-z][\\x2d0-9a-z]*\\x2e)+[1-9][0-9]*\\x3a[a-z][\\x2d0-9a-z]*\\x3a[\\x2d0-9A-Z\\x5fa-z]+",
        "action_type": "(?:[a-z][\\x2d0-9a-z]*\\x2e)+[1-9][0-9]*",
        "suite": "[a-z][\\x2d0-9a-z]*",
        "digest": "[\\x2d0-9A-Z\\x5fa-z]+",
        "amount_string": "\\x2d?(?:0|[1-9][0-9]*)(?:\\x2e[0-9]+)?",
        "digest_field": "sha256\\x3a[0-9a-f]{64}",
        "timestamp": "[0-9]{4}\\x2d(?:0[1-9]|1[0-2])\\x2d(?:0[1-9]|[12][0-9]|3[01])T(?:[01][0-9]|2[0-3])\\x3a[0-5][0-9]\\x3a[0-5][0-9](?:\\x2e[0-9]+)?Z",
        "format_name": "[a-z][\\x2d0-9a-z]*",
        "code_system": "[A-Za-z][\\x2b\\x2d\\x2e0-9A-Za-z]*\\x3a(?:[\\x21\\x24\\x26-\\x3b\\x3d\\x3f-Z\\x5fa-z\\x7e]|\\x25[0-9A-Fa-f][0-9A-Fa-f])+",
        "array_index": "(?:0|[1-9][0-9]*)",
        "hex_sha256": "[0-9a-f]{64}",
    },
    "pattern_max_octets": {
        "caid": 1024,
        "action_type": 512,
        "code_system": 2048,
    },
    "code_formats": {
        "icd-10-cm": "[A-Z][0-9A-Z]{2}(?:\\x2e[0-9A-Z]{1,4})?",
        "ndc-11": "[0-9]{11}",
        "ndc-10-hyphenated": "(?:[0-9]{4}\\x2d[0-9]{4}\\x2d[0-9]{2}|[0-9]{5}\\x2d[0-9]{4}\\x2d[0-9]|[0-9]{5}\\x2d[0-9]{3}\\x2d[0-9]{2})",
        "cpt": "[0-9]{4}[0-9A-Z]",
        "hcpcs-level-ii": "[A-Z][0-9]{4}",
        "hcpcs": "(?:[0-9]{4}[0-9A-Z]|[A-Z][0-9]{4})",
        "iso-3166-2": "[A-Z]{2}\\x2d[0-9A-Z]{1,3}",
        "iso20022-external-code": "[0-9A-Z]{1,4}",
        "nacha-sec": "[0-9A-Z]{3}",
    },
    "suites": (
        {
            "suite": "jcs-sha256",
            "digest_octets": 32,
            "digest_length": 43,
            "digest_pattern": "[\\x2d0-9A-Z\\x5fa-z]{42}[048AEIMQUYcgkosw]",
        },
        {
            "suite": "cbor-sha256",
            "digest_octets": 32,
            "digest_length": 43,
            "digest_pattern": "[\\x2d0-9A-Z\\x5fa-z]{42}[048AEIMQUYcgkosw]",
        },
    ),
    "timestamp_date_offsets": {
        "year": (0, 4),
        "month": (5, 7),
        "day": (8, 10),
    },
    "limits": {
        "json_text_octets": 33554432,
        "nesting_depth": 64,
        "canonical_octets": 16777216,
        "max_safe_integer": 9007199254740991,
        "value_count": 33554432,
        "document_canonical_octets": 134217728,
        "caid_octets": 1024,
        "action_type_octets": 512,
        "code_system_octets": 2048,
        "mapping_rules_min": 1,
        "mapping_rules_max": 128,
        "mapping_pointer_octets_max": 2048,
        "mapping_string_octets_min": 1,
        "mapping_string_octets_max": 512,
        "mapping_omission_reason_octets_min": 1,
        "mapping_omission_reason_octets_max": 2048,
    },
    "json_text": {
        "byte_order_mark": (239, 187, 191),
        "whitespace": (32, 9, 10, 13),
        "noncharacter_ranges": (
            (64976, 65007),
            (65534, 65535),
            (131070, 131071),
            (196606, 196607),
            (262142, 262143),
            (327678, 327679),
            (393214, 393215),
            (458750, 458751),
            (524286, 524287),
            (589822, 589823),
            (655358, 655359),
            (720894, 720895),
            (786430, 786431),
            (851966, 851967),
            (917502, 917503),
            (983038, 983039),
            (1048574, 1048575),
            (1114110, 1114111),
        ),
    },
    "reasons": ("malformed_json", "malformed_caid", "unknown_suite", "invalid_action_type", "unknown_action_type", "invalid_definition", "definition_mismatch", "missing_material_field", "mistyped_field", "invalid_amount", "invalid_code", "unsupported_number", "unsupported_value", "action_type_mismatch", "digest_mismatch", "invalid_object"),
    "reason_params": {
        "malformed_json": "none",
        "malformed_caid": "none",
        "unknown_suite": "none",
        "invalid_action_type": "none",
        "unknown_action_type": "none",
        "invalid_definition": "none",
        "definition_mismatch": "none",
        "missing_material_field": "field-name",
        "mistyped_field": "field-name",
        "invalid_amount": "field-name",
        "invalid_code": "field-name",
        "unsupported_number": "none",
        "unsupported_value": "none",
        "action_type_mismatch": "none",
        "digest_mismatch": "none",
        "invalid_object": "none",
    },
    "operations": {
        "decode": (
            {
                "rank": 0,
                "gate": True,
                "reasons": ("malformed_json",),
            },
        ),
        "parse": (
            {
                "rank": 1,
                "gate": True,
                "reasons": ("malformed_caid", "unknown_suite"),
                "steps": (
                    {
                        "check": "caid-rule",
                        "reason": "malformed_caid",
                    },
                    {
                        "check": "suite-registered",
                        "reason": "unknown_suite",
                    },
                    {
                        "check": "suite-digest-syntax",
                        "reason": "malformed_caid",
                    },
                ),
            },
        ),
        "compute": (
            {
                "rank": 0,
                "gate": True,
                "entry": "json_text",
                "reasons": ("malformed_json",),
            },
            {
                "rank": 1,
                "gate": True,
                "reasons": ("invalid_action_type",),
            },
            {
                "rank": 2,
                "gate": True,
                "reasons": ("unknown_action_type", "invalid_definition"),
            },
            {
                "rank": 3,
                "gate": False,
                "reasons": ("missing_material_field",),
                "position": "required_fields",
            },
            {
                "rank": 4,
                "gate": False,
                "reasons": ("mistyped_field", "invalid_amount", "invalid_code"),
                "position": "required_then_optional_fields",
                "per_position_max": 1,
            },
            {
                "rank": 5,
                "gate": False,
                "reasons": ("unknown_suite",),
            },
            {
                "rank": 6,
                "gate": False,
                "reasons": ("unsupported_number",),
            },
            {
                "rank": 7,
                "gate": False,
                "reasons": ("unsupported_value",),
            },
        ),
        "verify": (
            {
                "rank": 1,
                "gate": True,
                "entry": "parse",
                "reasons": ("malformed_caid", "unknown_suite"),
            },
            {
                "rank": 2,
                "gate": True,
                "entry": "json_text",
                "reasons": ("malformed_json",),
            },
            {
                "rank": 3,
                "gate": True,
                "reasons": ("invalid_object",),
            },
            {
                "rank": 4,
                "gate": False,
                "reasons": ("action_type_mismatch",),
            },
            {
                "rank": 5,
                "gate": False,
                "reasons": ("definition_mismatch",),
            },
            {
                "rank": 6,
                "gate": False,
                "reasons": ("unknown_suite", "digest_mismatch"),
                "per_position_max": 1,
            },
            {
                "rank": 7,
                "gate": False,
                "reasons": ("invalid_object",),
            },
        ),
    },
    "gates": {
        "decode": (
            ("malformed_json",),
        ),
        "parse": (
            ("malformed_caid", "unknown_suite"),
        ),
        "compute": (
            ("malformed_json",),
            ("invalid_action_type",),
            ("unknown_action_type", "invalid_definition"),
        ),
        "verify": (
            ("malformed_caid", "unknown_suite"),
            ("malformed_json",),
            ("invalid_object",),
        ),
    },
    "sort_rank": {
        "decode": {},
        "parse": {},
        "compute": {
            "missing_material_field": 3,
            "mistyped_field": 4,
            "invalid_amount": 4,
            "invalid_code": 4,
            "unknown_suite": 5,
            "unsupported_number": 6,
            "unsupported_value": 7,
        },
        "verify": {
            "action_type_mismatch": 4,
            "definition_mismatch": 5,
            "unknown_suite": 6,
            "digest_mismatch": 6,
            "invalid_object": 7,
        },
    },
    "position": {
        "decode": {},
        "parse": {},
        "compute": {
            "missing_material_field": "required_fields",
            "mistyped_field": "required_then_optional_fields",
            "invalid_amount": "required_then_optional_fields",
            "invalid_code": "required_then_optional_fields",
        },
        "verify": {},
    },
    "per_position_max": {
        "decode": {},
        "parse": {},
        "compute": {
            "mistyped_field": 1,
            "invalid_amount": 1,
            "invalid_code": 1,
        },
        "verify": {
            "unknown_suite": 1,
            "digest_mismatch": 1,
        },
    },
    "results": {
        "decode": {
            "accepted": ("ok", "value"),
            "refused": ("ok", "refusals"),
        },
        "parse": {
            "accepted": ("ok", "caid"),
            "refused": ("ok", "refusals"),
            "caid_members": ("version", "action_type", "suite", "digest"),
        },
        "compute": {
            "accepted": ("caid", "digest", "definition_sha256"),
            "refused": ("refusals",),
        },
        "verify": {
            "members": ("valid", "reasons", "details"),
            "optional_members": ("definition_sha256",),
        },
        "definition_sha256": {
            "accepted": ("definition_sha256",),
            "refused": ("refusals",),
            "refusal": "invalid_definition",
        },
    },
    "options": {
        "compute": ("suite", "definitions", "enum_snapshots"),
        "verify": ("definitions", "enum_snapshots", "expected_definition_sha256"),
    },
    "verify_details": {
        "members": ("reason", "field", "rule", "observed"),
        "expand": {
            "invalid_object": {
                "operation": "compute",
                "omit": ("unknown_suite",),
            },
        },
        "field_sources": ("param", "action_type"),
        "observed_sources": ("member", "argument"),
        "observed_kinds": ("absent", "null", "boolean", "number", "string", "array", "object", "unsupported"),
        "reasons": {
            "malformed_caid": {
                "rule": "caid",
                "field": None,
                "observed": "argument",
            },
            "unknown_suite": {
                "rule": "suite",
                "field": None,
                "observed": None,
            },
            "malformed_json": {
                "rule": "json-text",
                "field": None,
                "observed": None,
            },
            "action_type_mismatch": {
                "rule": "action-type-equal",
                "field": "action_type",
                "observed": "member",
            },
            "definition_mismatch": {
                "rule": "definition-sha256",
                "field": None,
                "observed": None,
            },
            "digest_mismatch": {
                "rule": "digest-equal",
                "field": None,
                "observed": None,
            },
            "invalid_action_type": {
                "rule": "action-type",
                "field": "action_type",
                "observed": "member",
            },
            "unknown_action_type": {
                "rule": "definition-resolution",
                "field": None,
                "observed": None,
            },
            "invalid_definition": {
                "rule": "definition-conformance",
                "field": None,
                "observed": None,
            },
            "missing_material_field": {
                "rule": "required-field",
                "field": "param",
                "observed": "member",
            },
            "mistyped_field": {
                "rule": "field-type",
                "field": "param",
                "observed": "member",
            },
            "invalid_amount": {
                "rule": "amount-string",
                "field": "param",
                "observed": "member",
            },
            "invalid_code": {
                "rule": "code-format",
                "field": "param",
                "observed": "member",
            },
            "unsupported_number": {
                "rule": "number",
                "field": None,
                "observed": None,
            },
            "unsupported_value": {
                "rule": "data-model",
                "field": None,
                "observed": None,
            },
        },
    },
    "field_types": (
        {
            "type": "string",
            "json": "string",
            "members": (),
            "required_members": {},
        },
        {
            "type": "amount-string",
            "json": "string",
            "members": (),
            "required_members": {},
            "pattern": "amount_string",
            "pattern_refusal": "invalid_amount",
        },
        {
            "type": "digest",
            "json": "string",
            "members": (),
            "required_members": {},
            "pattern": "digest_field",
            "pattern_refusal": "mistyped_field",
        },
        {
            "type": "enum",
            "json": "string",
            "members": ("values", "values_ref", "values_snapshot", "values_sha256"),
            "required_members": {},
        },
        {
            "type": "code",
            "json": "string",
            "members": ("code_system", "format"),
            "required_members": {
                "code_system": "code_system",
                "format": "format_name",
            },
            "format_refusal": "invalid_code",
            "unregistered_format_refusal": "mistyped_field",
        },
        {
            "type": "timestamp",
            "json": "string",
            "members": (),
            "required_members": {},
            "pattern": "timestamp",
            "pattern_refusal": "mistyped_field",
            "calendar_check": "day_within_month",
        },
        {
            "type": "integer",
            "json": "number",
            "members": (),
            "required_members": {},
        },
        {
            "type": "boolean",
            "json": "boolean",
            "members": (),
            "required_members": {},
        },
        {
            "type": "object",
            "json": "object",
            "members": (),
            "required_members": {},
        },
        {
            "type": "array",
            "json": "array",
            "members": (),
            "required_members": {},
        },
    ),
    "unknown_field_type_refusal": "mistyped_field",
    "definition": {
        "field_lists": ("required_fields", "optional_fields"),
        "required_fields_min": 1,
        "field_common_members": ("name", "type", "notes"),
        "field_name": {
            "rule": "field-name",
            "min_length": 1,
            "forbidden_code_points": (58,),
            "reserved": ("action_type",),
            "unique_across": ("required_fields", "optional_fields"),
        },
        "resolution": {
            "match_member": "action_type",
            "none": "unknown_action_type",
            "conflict": "invalid_definition",
            "nonconforming": "invalid_definition",
        },
        "projection": {
            "members": ("action_type", "required_fields", "optional_fields"),
            "defaults": {
                "optional_fields": (),
            },
            "field_members_excluded": ("notes",),
            "prefix": "sha256:",
        },
        "status_values": ("active", "deprecated"),
        "status_affects_computation": False,
        "registry_entry_members": ("action_type", "status", "risk_class", "summary", "required_fields", "optional_fields", "digest_notes", "references", "supersedes", "superseded_by"),
    },
    "enum": {
        "inline_prefix": "inline:",
        "inline_separator": "|",
        "inline_trim": (" ",),
    },
    "mapping": {
        "profile_version": "CAID-MAPPING-PROFILE-v1",
        "members": {
            "profile": ("@version", "profile_id", "source_format", "target_action_type", "loss_policy", "omitted_source_fields", "material_source_paths", "rules"),
            "source_format": ("media_type", "schema", "version"),
            "rule": ("source_path", "target_field", "transform"),
            "omitted_source_field": ("source_path", "reason"),
        },
        "optional_members": {
            "profile": ("omitted_source_fields",),
        },
        "null_member_refusal": "invalid_mapping_profile",
        "member_rules": (
            {
                "path": ("profile_id",),
                "json": "string",
                "min_octets": "mapping_string_octets_min",
                "max_octets": "mapping_string_octets_max",
            },
            {
                "path": ("source_format", "media_type"),
                "json": "string",
                "min_octets": "mapping_string_octets_min",
                "max_octets": "mapping_string_octets_max",
            },
            {
                "path": ("source_format", "schema"),
                "json": "string",
                "min_octets": "mapping_string_octets_min",
                "max_octets": "mapping_string_octets_max",
            },
            {
                "path": ("source_format", "version"),
                "json": "string",
                "min_octets": "mapping_string_octets_min",
                "max_octets": "mapping_string_octets_max",
            },
            {
                "path": ("target_action_type",),
                "json": "string",
                "min_octets": "mapping_string_octets_min",
                "max_octets": "mapping_string_octets_max",
            },
            {
                "path": ("loss_policy",),
                "json": "string",
                "closed": "loss_policies",
            },
            {
                "path": ("rules",),
                "json": "array",
                "min_items": "mapping_rules_min",
                "max_items": "mapping_rules_max",
            },
            {
                "path": ("rules", "*", "source_path"),
                "json": "string",
                "rule": "source-path",
                "max_octets": "mapping_pointer_octets_max",
            },
            {
                "path": ("rules", "*", "target_field"),
                "json": "string",
                "rule": "field-name",
                "reserved": ("action_type",),
            },
            {
                "path": ("rules", "*", "transform"),
                "json": "string",
                "closed": "transforms",
            },
            {
                "path": ("material_source_paths",),
                "json": "array",
                "min_items": "mapping_rules_min",
            },
            {
                "path": ("material_source_paths", "*"),
                "json": "string",
                "rule": "source-path",
                "max_octets": "mapping_pointer_octets_max",
            },
            {
                "path": ("omitted_source_fields",),
                "json": "array",
            },
            {
                "path": ("omitted_source_fields", "*", "source_path"),
                "json": "string",
                "rule": "source-path",
                "max_octets": "mapping_pointer_octets_max",
            },
            {
                "path": ("omitted_source_fields", "*", "reason"),
                "json": "string",
                "min_octets": "mapping_omission_reason_octets_min",
                "max_octets": "mapping_omission_reason_octets_max",
            },
        ),
        "unique": (
            ("rules", "*", "source_path"),
            ("rules", "*", "target_field"),
            ("material_source_paths", "*"),
            ("omitted_source_fields", "*", "source_path"),
        ),
        "equal_sets": (
            (
                ("rules", "*", "source_path"),
                ("material_source_paths", "*"),
            ),
        ),
        "disjoint": (
            (
                ("omitted_source_fields", "*", "source_path"),
                ("rules", "*", "source_path"),
            ),
        ),
        "transforms": (
            {
                "transform": "copy",
                "input": "any",
            },
            {
                "transform": "sha256-utf8",
                "input": "string",
            },
            {
                "transform": "sha256-jcs",
                "input": "any",
            },
            {
                "transform": "sha256-hex-to-digest",
                "input": "string",
                "pattern": "hex_sha256",
            },
        ),
        "loss_policies": (
            {
                "policy": "no-material-field-loss",
                "omitted_source_fields": "absent_or_empty",
            },
            {
                "policy": "declared-source-semantic-loss",
                "omitted_source_fields": "non_empty",
                "stage_reason": "declared_source_semantic_loss",
            },
        ),
        "verdicts": ("EQUIVALENT_UNDER_PROFILE", "NOT_EQUIVALENT", "INDETERMINATE"),
        "reasons": (
            {
                "code": "invalid_mapping_profile",
                "param": "none",
            },
            {
                "code": "unknown_action_type",
                "param": "none",
            },
            {
                "code": "invalid_definition",
                "param": "none",
            },
            {
                "code": "unmapped_material_field",
                "param": "field-name",
            },
            {
                "code": "native_verification_required",
                "param": "none",
            },
            {
                "code": "mapping_profile_unpinned",
                "param": "none",
            },
            {
                "code": "source_format_mismatch",
                "param": "none",
            },
            {
                "code": "source_not_object",
                "param": "none",
            },
            {
                "code": "source_not_canonicalizable",
                "param": "none",
            },
            {
                "code": "declared_source_semantic_loss",
                "param": "none",
            },
            {
                "code": "invalid_source_path",
                "param": "source-path",
            },
            {
                "code": "missing_source_field",
                "param": "source-path",
            },
            {
                "code": "source_value_type_mismatch",
                "param": "source-path",
            },
            {
                "code": "source_value_not_canonicalizable",
                "param": "source-path",
            },
            {
                "code": "unknown_transform",
                "param": "source-path",
            },
            {
                "code": "mapped_action",
                "param": "compute-reason",
            },
            {
                "code": "target_action_type_mismatch",
                "param": "none",
            },
            {
                "code": "material_projection_mismatch",
                "param": "none",
            },
        ),
        "stages": (
            {
                "stage": "A",
                "reasons": ("invalid_mapping_profile", "unknown_action_type", "invalid_definition", "unmapped_material_field"),
                "position": {
                    "unmapped_material_field": "required_fields",
                },
            },
            {
                "stage": "B",
                "reasons": ("native_verification_required", "mapping_profile_unpinned", "source_format_mismatch", "source_not_object", "source_not_canonicalizable", "declared_source_semantic_loss"),
            },
            {
                "stage": "C",
                "reasons": ("invalid_source_path", "missing_source_field", "source_value_type_mismatch", "source_value_not_canonicalizable", "unknown_transform"),
                "position": "rules",
                "per_position_max": 1,
            },
            {
                "stage": "D",
                "reasons": ("mapped_action",),
                "order": "compute",
            },
        ),
        "comparison": {
            "prefixes": ("left", "right"),
            "reasons": ("target_action_type_mismatch", "material_projection_mismatch"),
            "prefixed_verdict": "INDETERMINATE",
            "reason_verdicts": {
                "target_action_type_mismatch": "INDETERMINATE",
                "material_projection_mismatch": "NOT_EQUIVALENT",
            },
        },
        "fault_reasons": ("unexpected_mapping_error", "invalid_mapped_action"),
        "reason_params": {
            "invalid_mapping_profile": "none",
            "unknown_action_type": "none",
            "invalid_definition": "none",
            "unmapped_material_field": "field-name",
            "native_verification_required": "none",
            "mapping_profile_unpinned": "none",
            "source_format_mismatch": "none",
            "source_not_object": "none",
            "source_not_canonicalizable": "none",
            "declared_source_semantic_loss": "none",
            "invalid_source_path": "source-path",
            "missing_source_field": "source-path",
            "source_value_type_mismatch": "source-path",
            "source_value_not_canonicalizable": "source-path",
            "unknown_transform": "source-path",
            "mapped_action": "compute-reason",
            "target_action_type_mismatch": "none",
            "material_projection_mismatch": "none",
        },
        "reason_rank": {
            "invalid_mapping_profile": 0,
            "unknown_action_type": 1,
            "invalid_definition": 2,
            "unmapped_material_field": 3,
            "native_verification_required": 4,
            "mapping_profile_unpinned": 5,
            "source_format_mismatch": 6,
            "source_not_object": 7,
            "source_not_canonicalizable": 8,
            "declared_source_semantic_loss": 9,
            "invalid_source_path": 10,
            "missing_source_field": 11,
            "source_value_type_mismatch": 12,
            "source_value_not_canonicalizable": 13,
            "unknown_transform": 14,
            "mapped_action": 15,
        },
        "stage_of": {
            "invalid_mapping_profile": "A",
            "unknown_action_type": "A",
            "invalid_definition": "A",
            "unmapped_material_field": "A",
            "native_verification_required": "B",
            "mapping_profile_unpinned": "B",
            "source_format_mismatch": "B",
            "source_not_object": "B",
            "source_not_canonicalizable": "B",
            "declared_source_semantic_loss": "B",
            "invalid_source_path": "C",
            "missing_source_field": "C",
            "source_value_type_mismatch": "C",
            "source_value_not_canonicalizable": "C",
            "unknown_transform": "C",
            "mapped_action": "D",
        },
    },
})

# Whole-string matchers: each is \A(?:R)\Z over the portable expression R
# in SPEC["patterns"]. They refuse a value followed by a final line feed
# whichever of match, search, or fullmatch is used. Apply them to str only.
PATTERNS = types.MappingProxyType({
    "caid": re.compile("\\A(?:caid\\x3a1\\x3a(?:[a-z][\\x2d0-9a-z]*\\x2e)+[1-9][0-9]*\\x3a[a-z][\\x2d0-9a-z]*\\x3a[\\x2d0-9A-Z\\x5fa-z]+)\\Z"),
    "action_type": re.compile("\\A(?:(?:[a-z][\\x2d0-9a-z]*\\x2e)+[1-9][0-9]*)\\Z"),
    "suite": re.compile("\\A(?:[a-z][\\x2d0-9a-z]*)\\Z"),
    "digest": re.compile("\\A(?:[\\x2d0-9A-Z\\x5fa-z]+)\\Z"),
    "amount_string": re.compile("\\A(?:\\x2d?(?:0|[1-9][0-9]*)(?:\\x2e[0-9]+)?)\\Z"),
    "digest_field": re.compile("\\A(?:sha256\\x3a[0-9a-f]{64})\\Z"),
    "timestamp": re.compile("\\A(?:[0-9]{4}\\x2d(?:0[1-9]|1[0-2])\\x2d(?:0[1-9]|[12][0-9]|3[01])T(?:[01][0-9]|2[0-3])\\x3a[0-5][0-9]\\x3a[0-5][0-9](?:\\x2e[0-9]+)?Z)\\Z"),
    "format_name": re.compile("\\A(?:[a-z][\\x2d0-9a-z]*)\\Z"),
    "code_system": re.compile("\\A(?:[A-Za-z][\\x2b\\x2d\\x2e0-9A-Za-z]*\\x3a(?:[\\x21\\x24\\x26-\\x3b\\x3d\\x3f-Z\\x5fa-z\\x7e]|\\x25[0-9A-Fa-f][0-9A-Fa-f])+)\\Z"),
    "array_index": re.compile("\\A(?:(?:0|[1-9][0-9]*))\\Z"),
    "hex_sha256": re.compile("\\A(?:[0-9a-f]{64})\\Z"),
})

# Whole-string matcher of each registered code format, keyed by format name.
CODE_FORMATS = types.MappingProxyType({
    "icd-10-cm": re.compile("\\A(?:[A-Z][0-9A-Z]{2}(?:\\x2e[0-9A-Z]{1,4})?)\\Z"),
    "ndc-11": re.compile("\\A(?:[0-9]{11})\\Z"),
    "ndc-10-hyphenated": re.compile("\\A(?:(?:[0-9]{4}\\x2d[0-9]{4}\\x2d[0-9]{2}|[0-9]{5}\\x2d[0-9]{4}\\x2d[0-9]|[0-9]{5}\\x2d[0-9]{3}\\x2d[0-9]{2}))\\Z"),
    "cpt": re.compile("\\A(?:[0-9]{4}[0-9A-Z])\\Z"),
    "hcpcs-level-ii": re.compile("\\A(?:[A-Z][0-9]{4})\\Z"),
    "hcpcs": re.compile("\\A(?:(?:[0-9]{4}[0-9A-Z]|[A-Z][0-9]{4}))\\Z"),
    "iso-3166-2": re.compile("\\A(?:[A-Z]{2}\\x2d[0-9A-Z]{1,3})\\Z"),
    "iso20022-external-code": re.compile("\\A(?:[0-9A-Z]{1,4})\\Z"),
    "nacha-sec": re.compile("\\A(?:[0-9A-Z]{3})\\Z"),
})

# Registered suites and their digest lengths in octets.
SUITE_DIGEST_OCTETS = types.MappingProxyType({
    "jcs-sha256": 32,
    "cbor-sha256": 32,
})

# Digest syntax of each registered suite, keyed by suite name.
SUITE_DIGEST_PATTERNS = types.MappingProxyType({
    "jcs-sha256": re.compile("\\A(?:[\\x2d0-9A-Z\\x5fa-z]{42}[048AEIMQUYcgkosw])\\Z"),
    "cbor-sha256": re.compile("\\A(?:[\\x2d0-9A-Z\\x5fa-z]{42}[048AEIMQUYcgkosw])\\Z"),
})

# Limits, keyed by core.json limit id.
LIMITS = SPEC["limits"]
