# SPDX-License-Identifier: Apache-2.0
"""EP-WITNESS-v1 cosignature parity test (port of packages/verify/witness.test.js).

Proves the Python verifier reaches the SAME accept/refuse decisions as the JS
reference, AND that a cosignature PRODUCED IN JAVASCRIPT (fixed Ed25519 seeds,
signed over witnessSigningDigest) verifies HERE over byte-identical committed
bytes — the "JS-produced cosignature verifies in Python and vice versa" claim.

    pytest packages/python-verify/tests/test_witness.py
"""
import base64
import hashlib
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from cryptography.hazmat.primitives import serialization  # noqa: E402
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey  # noqa: E402

from emilia_verify import (  # noqa: E402
    canonicalize,
    verify_witness_cosignature,
    require_witness_quorum,
    witness_signing_digest,
    WITNESS_DOMAIN_TAG,
    WITNESS_VERSION,
)


def _b64u(b: bytes) -> str:
    return base64.urlsafe_b64encode(b).decode().rstrip("=")


def new_ed25519(seed: bytes = None):
    priv = Ed25519PrivateKey.from_private_bytes(seed) if seed else Ed25519PrivateKey.generate()
    pub = priv.public_key().public_bytes(
        serialization.Encoding.DER, serialization.PublicFormat.SubjectPublicKeyInfo
    )
    return {"priv": priv, "pub": _b64u(pub)}


def make_checkpoint(**overrides):
    cp = {
        "tree_size": 42,
        "root_hash": "sha256:" + "a1" * 32,
        "log_key_id": "ep:log:test#1",
        "merkle_alg": "EP-MERKLE-v2",
    }
    cp.update(overrides)
    return cp


def cosign(cp, witness_id, keys, extra=None):
    digest = witness_signing_digest(cp)
    signature = _b64u(keys["priv"].sign(digest))
    out = {
        "alg": WITNESS_VERSION,
        "witness_id": witness_id,
        "tree_size": cp["tree_size"],
        "root_hash": cp["root_hash"],
        "log_key_id": cp["log_key_id"],
        "signature": signature,
    }
    if extra:
        out.update(extra)
    return out


# ── cross-language: JS-produced cosignature verifies in Python ────────────────
# Generated by packages/verify (fixed seeds 0x11../0x22../0x33..), signed over
# witnessSigningDigest(CHECKPOINT). Byte-identical committed bytes both sides.
_JS_CHECKPOINT = {
    "tree_size": 42,
    "root_hash": "sha256:a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1",
    "log_key_id": "ep:log:test#1",
    "merkle_alg": "EP-MERKLE-v2",
}
_JS_DIGEST_HEX = "f61a93dfed4f51c7ec939e59db1fb856bfad9c63134067ad3bd7f72d1cce611c"
_JS_PINNED = [
    {"witness_id": "a", "public_key": "MCowBQYDK2VwAyEA0EqyMnQrtKs6E2i9RhXk5tAiSrcaAWuvhSCjMsl3hzc"},
    {"witness_id": "b", "public_key": "MCowBQYDK2VwAyEAoJql9HpnWYAv-VX43C0qFKXJnSO-l_hkEn_5ODRVpPA"},
    {"witness_id": "c", "public_key": "MCowBQYDK2VwAyEAF8t5-ytBIPKx7GXkGY1uCLKOgT_rAeSkAIObheGAgM4"},
]
_JS_COSIGS = [
    {"alg": WITNESS_VERSION, "witness_id": "a", "tree_size": 42,
     "root_hash": _JS_CHECKPOINT["root_hash"], "log_key_id": "ep:log:test#1",
     "signature": "2PsVlxcySH8zfpzB7GvB63-GsL_2YJBQZrqNHcj4rpRzur_MfPPJ2u4IUuk_kH4eIGHKviTtcHtTkWBBi2vvAQ"},
    {"alg": WITNESS_VERSION, "witness_id": "b", "tree_size": 42,
     "root_hash": _JS_CHECKPOINT["root_hash"], "log_key_id": "ep:log:test#1",
     "signature": "_gpsv2NXzS7I98yNqLMShtH3tMSCGCB6zTB70SX8g1HGM529iU4BHHXpLHWAGnMlv-Ga8ob3KJ5rPqUEK7aTBQ"},
    {"alg": WITNESS_VERSION, "witness_id": "c", "tree_size": 42,
     "root_hash": _JS_CHECKPOINT["root_hash"], "log_key_id": "ep:log:test#1",
     "signature": "Jb9UTGH90XWL_JuztQAD_4nAPplWbdUIOWaOwL1X3EdE0nFKA-BP1hKme5n3P2Ez2oOnRDprLo82Vw5v3I5UAQ"},
]


def test_cross_language_js_digest_matches_python():
    assert witness_signing_digest(_JS_CHECKPOINT).hex() == _JS_DIGEST_HEX


def test_cross_language_js_cosignatures_verify_in_python():
    pinned_by_id = {p["witness_id"]: p for p in _JS_PINNED}
    for cs in _JS_COSIGS:
        r = verify_witness_cosignature(_JS_CHECKPOINT, cs, pinned_by_id[cs["witness_id"]])
        assert r["verified"] is True, cs["witness_id"]
        assert r["witness_id"] == cs["witness_id"]


def test_cross_language_js_quorum_in_python():
    r = require_witness_quorum(_JS_CHECKPOINT, _JS_COSIGS, _JS_PINNED, 2)
    assert r["ok"] is True
    assert r["met"] == 3
    assert r["witness_ids"] == ["a", "b", "c"]


# ── single-cosignature verification (Python-generated) ───────────────────────
def test_genuine_cosignature_verifies():
    w = new_ed25519()
    cp = make_checkpoint()
    r = verify_witness_cosignature(cp, cosign(cp, "witness-a", w),
                                   {"witness_id": "witness-a", "public_key": w["pub"]})
    assert r["verified"] is True
    assert r["witness_id"] == "witness-a"
    assert "reason" not in r


def test_cosignature_over_checkpoint_with_log_signature_still_verifies():
    w = new_ed25519()
    cp = make_checkpoint()
    cosig = cosign(cp, "witness-a", w)  # signed over committed bytes (no log_signature)
    with_log_sig = {**cp, "log_signature": "b64u:deadbeef"}
    r = verify_witness_cosignature(with_log_sig, cosig, {"witness_id": "witness-a", "public_key": w["pub"]})
    assert r["verified"] is True, "log_signature must be stripped before hashing"


def test_wrong_key_refuses():
    signer = new_ed25519()
    other = new_ed25519()
    cp = make_checkpoint()
    r = verify_witness_cosignature(cp, cosign(cp, "witness-a", signer),
                                   {"witness_id": "witness-a", "public_key": other["pub"]})
    assert r["verified"] is False
    assert "does not verify" in r["reason"]


def test_unpinned_witness_id_refuses():
    w = new_ed25519()
    cp = make_checkpoint()
    r = verify_witness_cosignature(cp, cosign(cp, "witness-stranger", w),
                                   {"witness_id": "witness-a", "public_key": w["pub"]})
    assert r["verified"] is False
    assert "unpinned witness refused" in r["reason"]


def test_tampered_checkpoint_refuses():
    w = new_ed25519()
    cp = make_checkpoint()
    cosig = cosign(cp, "witness-a", w)
    tampered = make_checkpoint(root_hash="sha256:" + "ff" * 32)
    bare = {k: v for k, v in cosig.items() if k != "root_hash"}
    r = verify_witness_cosignature(tampered, bare, {"witness_id": "witness-a", "public_key": w["pub"]})
    assert r["verified"] is False
    assert "does not verify over the checkpoint committed bytes" in r["reason"]


def test_tampered_tree_size_refuses():
    w = new_ed25519()
    cp = make_checkpoint()
    cosig = cosign(cp, "witness-a", w)
    bare = {k: v for k, v in cosig.items() if k != "tree_size"}
    tampered = make_checkpoint(tree_size=43)
    r = verify_witness_cosignature(tampered, bare, {"witness_id": "witness-a", "public_key": w["pub"]})
    assert r["verified"] is False


def test_cosignature_echoed_for_different_head_refuses_before_crypto():
    w = new_ed25519()
    cp = make_checkpoint(tree_size=42)
    cosig = cosign(cp, "witness-a", w)  # echoes tree_size 42
    other = make_checkpoint(tree_size=100)
    r = verify_witness_cosignature(other, cosig, {"witness_id": "witness-a", "public_key": w["pub"]})
    assert r["verified"] is False
    assert "different head" in r["reason"]


def test_cosignature_echoed_for_different_log_refuses():
    w = new_ed25519()
    cp = make_checkpoint(log_key_id="ep:log:test#1")
    cosig = cosign(cp, "witness-a", w)
    other = make_checkpoint(log_key_id="ep:log:evil#9")
    r = verify_witness_cosignature(other, cosig, {"witness_id": "witness-a", "public_key": w["pub"]})
    assert r["verified"] is False
    assert "different log" in r["reason"]


def test_domain_separation_log_signature_not_replayable():
    w = new_ed25519()
    cp = make_checkpoint()
    signed = {k: v for k, v in cp.items() if k != "log_signature"}
    log_digest = hashlib.sha256(canonicalize(signed).encode("utf-8")).digest()  # NO domain tag
    log_sig = _b64u(w["priv"].sign(log_digest))
    forged = {"alg": WITNESS_VERSION, "witness_id": "witness-a", "tree_size": cp["tree_size"],
              "root_hash": cp["root_hash"], "log_key_id": cp["log_key_id"], "signature": log_sig}
    r = verify_witness_cosignature(cp, forged, {"witness_id": "witness-a", "public_key": w["pub"]})
    assert r["verified"] is False, "a log signature must not be replayable as a witness cosignature"


def test_witness_preimage_includes_domain_tag():
    cp = make_checkpoint()
    signed = dict(cp)
    witness_pre = WITNESS_DOMAIN_TAG.encode("utf-8") + canonicalize(signed).encode("utf-8")
    expected = hashlib.sha256(witness_pre).digest()
    assert witness_signing_digest(cp) == expected
    log_digest = hashlib.sha256(canonicalize(signed).encode("utf-8")).digest()
    assert witness_signing_digest(cp) != log_digest


def test_malformed_inputs_refuse():
    w = new_ed25519()
    cp = make_checkpoint()
    good = cosign(cp, "witness-a", w)
    pin = {"witness_id": "witness-a", "public_key": w["pub"]}
    assert verify_witness_cosignature(None, good, pin)["verified"] is False
    assert verify_witness_cosignature(cp, None, pin)["verified"] is False
    assert verify_witness_cosignature(cp, good, None)["verified"] is False
    assert verify_witness_cosignature(cp, good, {"witness_id": "witness-a"})["verified"] is False
    assert verify_witness_cosignature(cp, good, {"public_key": w["pub"]})["verified"] is False
    assert verify_witness_cosignature(cp, {**good, "signature": None}, pin)["verified"] is False
    assert verify_witness_cosignature(cp, {**good, "witness_id": None}, pin)["verified"] is False
    assert verify_witness_cosignature(cp, {**good, "alg": "WRONG"}, pin)["verified"] is False


# ── k-of-n quorum helper ─────────────────────────────────────────────────────
def test_quorum_accepts_k_distinct():
    wA, wB, wC = new_ed25519(), new_ed25519(), new_ed25519()
    cp = make_checkpoint()
    pinned = [{"witness_id": "a", "public_key": wA["pub"]},
              {"witness_id": "b", "public_key": wB["pub"]},
              {"witness_id": "c", "public_key": wC["pub"]}]
    cosigs = [cosign(cp, "a", wA), cosign(cp, "b", wB), cosign(cp, "c", wC)]
    r = require_witness_quorum(cp, cosigs, pinned, 2)
    assert r["ok"] is True
    assert r["met"] == 3
    assert r["required"] == 2
    assert r["witness_ids"] == ["a", "b", "c"]


def test_quorum_refuses_k_minus_1():
    wA, wB, wC = new_ed25519(), new_ed25519(), new_ed25519()
    cp = make_checkpoint()
    pinned = [{"witness_id": "a", "public_key": wA["pub"]},
              {"witness_id": "b", "public_key": wB["pub"]},
              {"witness_id": "c", "public_key": wC["pub"]}]
    cosigs = [cosign(cp, "a", wA), cosign(cp, "b", wB)]
    r = require_witness_quorum(cp, cosigs, pinned, 3)
    assert r["ok"] is False
    assert r["met"] == 2
    assert r["required"] == 3


def test_quorum_counts_duplicate_once():
    wA, wB = new_ed25519(), new_ed25519()
    cp = make_checkpoint()
    pinned = [{"witness_id": "a", "public_key": wA["pub"]},
              {"witness_id": "b", "public_key": wB["pub"]}]
    cosigs = [cosign(cp, "a", wA), cosign(cp, "a", wA)]
    r = require_witness_quorum(cp, cosigs, pinned, 2)
    assert r["ok"] is False
    assert r["met"] == 1
    assert r["witness_ids"] == ["a"]
    assert 'duplicate cosignature from witness "a"' in " ".join(r["reasons"])


def test_quorum_ignores_unpinned():
    wA, wB, wStranger = new_ed25519(), new_ed25519(), new_ed25519()
    cp = make_checkpoint()
    pinned = [{"witness_id": "a", "public_key": wA["pub"]},
              {"witness_id": "b", "public_key": wB["pub"]}]
    cosigs = [cosign(cp, "a", wA), cosign(cp, "stranger", wStranger)]
    r = require_witness_quorum(cp, cosigs, pinned, 2)
    assert r["ok"] is False
    assert r["met"] == 1
    assert 'unpinned witness "stranger"' in " ".join(r["reasons"])


def test_quorum_ignores_different_head():
    wA, wB = new_ed25519(), new_ed25519()
    cp = make_checkpoint(tree_size=42)
    other = make_checkpoint(tree_size=99)
    pinned = [{"witness_id": "a", "public_key": wA["pub"]},
              {"witness_id": "b", "public_key": wB["pub"]}]
    cosigs = [cosign(cp, "a", wA), cosign(other, "b", wB)]
    r = require_witness_quorum(cp, cosigs, pinned, 2)
    assert r["ok"] is False
    assert r["met"] == 1
    assert r["witness_ids"] == ["a"]


def test_quorum_drops_ambiguous_pinned_duplicate():
    wA1, wA2, wB = new_ed25519(), new_ed25519(), new_ed25519()
    cp = make_checkpoint()
    pinned = [{"witness_id": "a", "public_key": wA1["pub"]},
              {"witness_id": "a", "public_key": wA2["pub"]},
              {"witness_id": "b", "public_key": wB["pub"]}]
    cosigs = [cosign(cp, "a", wA1), cosign(cp, "b", wB)]
    r = require_witness_quorum(cp, cosigs, pinned, 2)
    assert r["ok"] is False
    assert r["met"] == 1  # only "b"; "a" is unpinned after the drop
    assert "appears more than once" in " ".join(r["reasons"])


def test_quorum_fails_closed_on_bad_k_and_inputs():
    cp = make_checkpoint()
    assert require_witness_quorum(cp, [], [], 0)["ok"] is False
    assert require_witness_quorum(cp, [], [], 2.5)["ok"] is False
    assert require_witness_quorum(cp, [], [], "2")["ok"] is False
    assert require_witness_quorum(None, [], [], 1)["ok"] is False
    assert require_witness_quorum(cp, "nope", [], 1)["ok"] is False
    assert require_witness_quorum(cp, [], "nope", 1)["ok"] is False


if __name__ == "__main__":
    for name, fn in sorted(globals().items()):
        if name.startswith("test_") and callable(fn):
            fn()
    print("ALL PASS — EP-WITNESS-v1 parity (incl. JS-produced cosignature verified in Python)")
