"""Public API for the EMILIA Protocol Python SDK."""

from ._routes import ROUTE_CONTRACT
from ._version import __version__
from .client import DEFAULT_BASE_URL, EPClient, EPError
from .types import (
    AttestExecutionParams,
    ConsumeTrustReceiptParams,
    ConsumeTrustReceiptResult,
    CreateTrustReceiptParams,
    ExecutionAttestation,
    GateParams,
    GateResult,
    Handshake,
    InitiateHandshakeParams,
    MutationObservationContext,
    Party,
    Presentation,
    PresentParams,
    QuorumApprover,
    QuorumPolicy,
    ReceiptContext,
    RequestSignoffParams,
    RequireReceiptParams,
    RequireReceiptResult,
    RevokeResult,
    SignoffRequest,
    SignoffRequiredContext,
    TrustReceipt,
    TrustReceiptState,
    VerificationResult,
)

__all__ = [
    "AttestExecutionParams",
    "ConsumeTrustReceiptParams",
    "ConsumeTrustReceiptResult",
    "CreateTrustReceiptParams",
    "DEFAULT_BASE_URL",
    "EPClient",
    "EPError",
    "ExecutionAttestation",
    "GateParams",
    "GateResult",
    "Handshake",
    "InitiateHandshakeParams",
    "MutationObservationContext",
    "Party",
    "Presentation",
    "PresentParams",
    "QuorumApprover",
    "QuorumPolicy",
    "ROUTE_CONTRACT",
    "ReceiptContext",
    "RequestSignoffParams",
    "RequireReceiptParams",
    "RequireReceiptResult",
    "RevokeResult",
    "SignoffRequest",
    "SignoffRequiredContext",
    "TrustReceipt",
    "TrustReceiptState",
    "VerificationResult",
    "__version__",
]
