// SPDX-License-Identifier: Apache-2.0
//
//   node packages/scan/codemod.mjs <actions.json|openapi.json|--sample> [--out ./emilia] [--apply] [--force]
//
// Turns a scan into drop-in files: a reviewed action-control manifest and a
// runnable guard module you import at your tool-call choke point.
//
// SAFETY BOUNDARY (this is the whole point):
//   - DRY-RUN by default. It prints every file it WOULD write. Nothing is
//     touched until you pass --apply.
//   - It only ever CREATES NEW FILES under the output dir. It refuses to
//     overwrite an existing file unless you pass --force.
//   - It NEVER edits your existing source. The single call-site line is printed
//     as an instruction for you to apply, not silently spliced into your code.
//   - The generated guard fails closed: defaultIrreversible=true (any tool the
//     scan did not see is gated), and consent/signoff/issue adapters refuse
//     until you wire them. Nothing verifies until you pin issuer keys.
import fs from 'node:fs';
import path from 'node:path';
import { scanActions } from './index.js';

const SAMPLE = [
  { name: 'getAccountBalance', description: 'Return the current balance for an account' },
  { name: 'sendWire', description: 'Send an outgoing wire transfer to a beneficiary' },
  { name: 'deployToProduction', description: 'Ship the current build to production' },
  { name: 'deleteCustomer', description: 'Permanently remove a customer record' },
  { name: 'summarizeTicket', description: 'Summarize a support ticket', annotations: { readOnlyHint: true } },
  { name: 'reconcileLedger', description: 'Reconcile the internal ledger and post adjustments' },
];

function ingest(file) {
  const j = JSON.parse(fs.readFileSync(file, 'utf8'));
  if (j && j.openapi && j.paths) {
    const actions = [];
    for (const [p, ops] of Object.entries(j.paths)) {
      for (const [m, op] of Object.entries(ops)) {
        if (!['get', 'post', 'put', 'patch', 'delete'].includes(m)) continue;
        actions.push({ name: op?.operationId || `${m} ${p}`, description: op?.summary || '', http_method: m, route_path: p });
      }
    }
    return { actions, source: 'openapi' };
  }
  const list = Array.isArray(j) ? j : Array.isArray(j.tools) ? j.tools : null;
  if (!list) throw new Error('Unrecognized input.');
  return { actions: list, source: 'mcp' };
}

const args = process.argv.slice(2);
const flag = (f) => args.includes(f);
const opt = (f, d) => { const i = args.indexOf(f); return i >= 0 ? args[i + 1] : d; };
const outDir = opt('--out', 'emilia');
const apply = flag('--apply');
const force = flag('--force');

let input;
if (flag('--sample')) input = { actions: SAMPLE, source: 'mcp' };
else {
  const file = args.find((a) => !a.startsWith('--') && a !== outDir);
  if (!file) { console.error('usage: codemod.mjs <actions.json|--sample> [--out dir] [--apply] [--force]'); process.exit(2); }
  input = ingest(file);
}

const rep = scanActions(input.actions, { source: input.source });
const isHttp = input.source === 'openapi';

// Build the guard's per-tool annotations from the scan. Gated + fail-closed
// actions => irreversible:true; read-only => irreversible:false. Anything the
// scan never saw is caught by defaultIrreversible:true.
const annEntries = rep.results.map(({ action, classification: c }) => {
  const gated = c.decision === 'gate' || c.decision === 'review_fail_closed';
  const actionType = c.category ? (rep.manifest.actions.find((a) => a.match?.tool === action.name)?.action_type || action.name) : action.name;
  const note = c.decision === 'review_fail_closed' ? '  // REVIEW: unrecognized mutator, defaulted fail-closed — confirm or set false'
    : c.decision === 'gate' ? `  // ${c.assurance_class}` : '  // read-only';
  return gated
    ? `  ${JSON.stringify(action.name)}: { irreversible: true, action: ${JSON.stringify(actionType)} },${note}`
    : `  ${JSON.stringify(action.name)}: { irreversible: false },${note}`;
});

const guardJs = `// SPDX-License-Identifier: Apache-2.0
// GENERATED by @emilia-protocol/scan. REVIEW before use; correct any classification.
import { withMcpGuard } from '@emilia-protocol/mcp-guard';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const manifest = JSON.parse(readFileSync(join(here, 'action-control.manifest.json'), 'utf8'));

// Pin your issuer/approver public keys OUT OF BAND (comma-separated base64url SPKI).
// Until this is set, every gated action fails closed.
const trustedKeys = (process.env.EP_TRUSTED_ISSUER_KEYS || '').split(',').map((s) => s.trim()).filter(Boolean);

// Per-tool flags from the scan. Edit to correct any false positive/negative.
const annotations = {
${annEntries.join('\n')}
};

/** Wrap your MCP tool-call dispatcher. */
export function guardDispatch(dispatch) {
  if (trustedKeys.length === 0) {
    console.warn('[emilia] EP_TRUSTED_ISSUER_KEYS is empty — gated actions will be REFUSED until you pin keys.');
  }
  return withMcpGuard(dispatch, {
    annotations,
    defaultIrreversible: true, // fail closed: any tool the scan did not see is gated
    verifyOpts: { trustedKeys },
    enforceDemand: true,
    // Wire these adapters to your EP host / @emilia-protocol/issue. Until then, a
    // gated call arriving WITHOUT a valid receipt fails closed (is refused).
    // requestClassASignoff: async (ctx) => yourSignoff(ctx),
    // issueReceipt: async (ctx) => yourHost.issue(ctx),
  });
}

export { manifest };
`;

const integrationMd = `# EMILIA integration (generated)

0. Install the runtime guard: \`npm install @emilia-protocol/mcp-guard\`
1. Review \`action-control.manifest.json\` and the \`annotations\` in \`guard.mjs\`.
   Downgrade any false positive; confirm every action marked REVIEW.
2. Add ONE line at your MCP tool-call dispatch site:

\`\`\`js
import { guardDispatch } from './${outDir}/guard.mjs';
// before: const result = await dispatch(name, args, extra);
const dispatch = guardDispatch(rawDispatch);   // wrap once, at the choke point
\`\`\`

3. Pin keys: set \`EP_TRUSTED_ISSUER_KEYS\` to your issuer/approver public keys.
4. Wire the signoff/issue adapters in \`guard.mjs\` to your EP host.

Nothing is enforced until steps 2 and 3 are done. This scaffold proposes; it does
not protect on its own.
`;

// ---- HTTP guard for an OpenAPI surface (Express, requireEmiliaReceipt) ----
const toExpressPath = (p) => String(p || '/').replace(/\{([^}]+)\}/g, ':$1');
const routes = rep.results
  .filter((r) => r.classification.decision === 'gate' || r.classification.decision === 'review_fail_closed')
  .map((r) => ({
    method: String(r.action.http_method || 'post').toLowerCase(),
    path: toExpressPath(r.action.route_path),
    action: r.classification.category ? (rep.manifest.actions.find((a) => a.match?.tool === r.action.name)?.action_type || r.action.name) : r.action.name,
    tier: r.classification.assurance_class || 'class_a',
    review: r.classification.decision === 'review_fail_closed',
  }));
const reviewCount = routes.filter((r) => r.review).length;

const httpGuardJs = `// SPDX-License-Identifier: Apache-2.0
// GENERATED by @emilia-protocol/scan (emilia-harden). REVIEW before use.
import { requireEmiliaReceipt } from '@emilia-protocol/require-receipt';

// Pin your issuer/approver public keys OUT OF BAND (comma-separated base64url SPKI).
// Until set, every gated route fails closed (428 Receipt-Required on each request).
const trustedKeys = (process.env.EP_TRUSTED_ISSUER_KEYS || '').split(',').map((s) => s.trim()).filter(Boolean);

// Consequential routes from the scan. Each demands a valid receipt at its tier; a
// request without one gets HTTP 428 + a Receipt-Required challenge. Edit freely.
export const GATED_ROUTES = ${JSON.stringify(routes.map(({ review, ...r }) => r), null, 2)};

/** Apply one receipt gate per consequential route to an Express/Connect app. */
export function applyEmiliaGates(app) {
  if (trustedKeys.length === 0) {
    console.warn('[emilia] EP_TRUSTED_ISSUER_KEYS is empty — gated routes refuse every request until you pin keys.');
  }
  for (const r of GATED_ROUTES) {
    app[r.method](r.path, requireEmiliaReceipt({ action: r.action, assuranceClass: r.tier, statusCode: 428, trustedKeys }));
  }
  return app;
}
`;

const httpIntegrationMd = `# EMILIA integration (generated, HTTP / OpenAPI)

0. Install the runtime guard: \`npm install @emilia-protocol/require-receipt\`
1. Review \`action-control.manifest.json\` and \`GATED_ROUTES\` in \`http-guard.mjs\`.
   ${reviewCount ? `Confirm the ${reviewCount} route(s) marked review (mutating, unrecognized category — defaulted fail-closed).` : 'Downgrade any false positive.'}
2. Apply the gates BEFORE your route handlers:

\`\`\`js
import { applyEmiliaGates } from './${outDir}/http-guard.mjs';
applyEmiliaGates(app);   // one receipt gate per consequential route; returns 428 without a valid receipt
\`\`\`

3. Serve the manifest so agents can discover what to bring:
   \`app.get('/.well-known/agent-actions.json', (_req, res) => res.sendFile(new URL('./action-control.manifest.json', import.meta.url).pathname));\`
4. Pin keys: set \`EP_TRUSTED_ISSUER_KEYS\`. Nothing is enforced until steps 2 and 4 are done.
`;

const files = [
  { rel: path.join(outDir, 'action-control.manifest.json'), body: `${JSON.stringify(rep.manifest, null, 2)}\n` },
  { rel: path.join(outDir, isHttp ? 'http-guard.mjs' : 'guard.mjs'), body: isHttp ? httpGuardJs : guardJs },
  { rel: path.join(outDir, 'INTEGRATION.md'), body: isHttp ? httpIntegrationMd : integrationMd },
];

const B = '\x1b[1m'; const D = '\x1b[2m'; const R = '\x1b[0m'; const Y = '\x1b[33m';
console.log(`\n${B}EMILIA codemod — ${input.source} surface, ${rep.counts.total} actions ` +
  `(${rep.counts.gate} gated, ${rep.counts.review_fail_closed} fail-closed for review)${R}`);

if (!apply) {
  console.log(`${Y}DRY RUN — nothing written. Re-run with --apply to create these files.${R}\n`);
  for (const f of files) {
    console.log(`${B}── would create: ${f.rel} ──${R}`);
    console.log(f.body.split('\n').slice(0, 40).map((l) => `${D}| ${R}${l}`).join('\n'));
    if (f.body.split('\n').length > 40) console.log(`${D}| … (${f.body.split('\n').length - 40} more lines)${R}`);
    console.log('');
  }
  process.exit(0);
}

// --apply: create NEW files only, never clobber without --force.
const existing = files.filter((f) => fs.existsSync(f.rel));
if (existing.length && !force) {
  console.error(`${Y}Refusing to overwrite existing files (pass --force to replace):${R}`);
  for (const f of existing) console.error(`  ${f.rel}`);
  process.exit(1);
}
fs.mkdirSync(outDir, { recursive: true });
for (const f of files) { fs.writeFileSync(f.rel, f.body); console.log(`  wrote ${f.rel}`); }
console.log(`\n${B}Done.${R} Now do steps 2 and 3 in ${path.join(outDir, 'INTEGRATION.md')} — nothing is enforced until you do.\n`);
