// SPDX-License-Identifier: Apache-2.0

package caid

import (
	"reflect"
	"strings"
	"testing"

	"caid/internal/jsontext"
)

// The JSON text decoder lives in its own package, which cannot import the
// generated constants of this one, so it states the byte order mark, the
// JSON whitespace set and the noncharacters itself. These tests hold it to
// the generated data (caid/spec/core.json), so the two cannot drift.

func TestDecoderNoncharactersEqualTheGeneratedRanges(t *testing.T) {
	inRanges := func(r rune) bool {
		for _, rng := range specNoncharacterRanges {
			if r >= rng[0] && r <= rng[1] {
				return true
			}
		}
		return false
	}
	for r := rune(0); r <= 0x10FFFF; r++ {
		if jsontext.IsNoncharacter(r) != inRanges(r) {
			t.Fatalf("U+%04X: decoder says %v, core.json says %v", r, jsontext.IsNoncharacter(r), inRanges(r))
		}
	}
}

func TestDecoderByteOrderMarkAndWhitespaceEqualTheGeneratedData(t *testing.T) {
	if _, err := DecodeJSON(append(append([]byte{}, specJSONByteOrderMark...), '{', '}')); err == nil {
		t.Error("a text beginning with the generated byte order mark decoded")
	}
	for b := 0; b < 0x80; b++ {
		_, err := DecodeJSON([]byte{byte(b), '{', '}'})
		want := strings.IndexByte(string(specJSONWhitespace), byte(b)) >= 0
		if (err == nil) != want {
			t.Errorf("byte 0x%02X before the value: decoded=%v, JSON whitespace=%v", b, err == nil, want)
		}
	}
}

func TestPatternLengthLimitsComeFirst(t *testing.T) {
	// A string over its limit is refused before the pattern runs, however
	// long it is (draft -05 Section 2.6).
	long := strings.Repeat("a", 8_000_000) + ".1"
	if got := refusals(obj{"action_type": long, "c": "x"}, stringDefinition); !reflect.DeepEqual(got, []string{"invalid_action_type"}) {
		t.Errorf("8-million-octet action type: %v", got)
	}
	if got := ParseCaid("canactid:1:" + long + ":jcs-sha256:" + strings.Repeat("A", 43)); got.OK || !reflect.DeepEqual(got.Refusals, []string{"malformed_caid"}) {
		t.Errorf("8-million-octet CAID: %#v", got)
	}
	at := strings.Repeat("a", specPatternMaxOctets["action_type"]-2) + ".1"
	if !matchPattern("action_type", at) || matchPattern("action_type", "a"+at) {
		t.Error("the action type limit is not exactly specPatternMaxOctets")
	}
}

func TestMappingSuccessCarriesDefinitionSha256(t *testing.T) {
	result := mapWith(mapProfile(), mapSource(), nil)
	want := DefinitionSha256(mapDefinitions[0]).DefinitionSha256
	if !result.OK || result.DefinitionSha256 == "" || result.DefinitionSha256 != want {
		t.Fatalf("MapAction definition_sha256 = %q, want %q (%v)", result.DefinitionSha256, want, result.Reasons)
	}
}

func TestMappingProfileOutsideTheDataModelIsAShapeFailure(t *testing.T) {
	// The profile keeps one rule, so a later stage A check would add
	// unmapped_material_field:b if the shape gate let it through.
	for _, id := range []string{"\uffff", "\xed\xa0\x80", "\U0010FFFF"} {
		got := mapReasons(func(p obj) {
			p["profile_id"] = id
			p["rules"] = []interface{}{obj{"source_path": "/x/a", "target_field": "a", "transform": "copy"}}
			p["material_source_paths"] = []interface{}{"/x/a"}
		})
		want := []string{"invalid_mapping_profile", "mapping_profile_unpinned"}
		if !reflect.DeepEqual(got, want) {
			t.Errorf("profile_id %q: %v, want %v", id, got, want)
		}
	}
}
