// Code generated by caid/spec/gen.mjs; DO NOT EDIT.

// Derived from caid/spec/caid.abnf, caid/spec/core.json, caid/registry/suites.json.
// The draft is the normative text; these constants are generated from it.
// Regenerate with: node caid/spec/gen.mjs --write

package caid

import "regexp"

// specIdentifierScheme is the caid rule's fixed scheme.
const specIdentifierScheme = "canactid"

// specIdentifierLegacyV04Scheme is the obsolete CAID-04 scheme accepted only by explicit legacy verification.
const specIdentifierLegacyV04Scheme = "caid"

// specIdentifierVersion is the caid rule's caid-version.
const specIdentifierVersion = "1"

// specIdentifierSeparator separates the caid rule's parts.
const specIdentifierSeparator = ":"

// specIdentifierParts is the number of separator-delimited parts of a CAID.
const specIdentifierParts = 5

// Whole-string matchers: ^(?:R)$ over each portable expression R. Without
// the m flag, RE2 matches $ only at the end of the text.
var specPatternCaid = regexp.MustCompile(`^(?:canactid\x3a1\x3a(?:[a-z][\x2d0-9a-z]*\x2e)+[1-9][0-9]*\x3a[a-z][\x2d0-9a-z]*\x3a[\x2d0-9A-Z\x5fa-z]+)$`)

var specPatternActionType = regexp.MustCompile(`^(?:(?:[a-z][\x2d0-9a-z]*\x2e)+[1-9][0-9]*)$`)

var specPatternSuite = regexp.MustCompile(`^(?:[a-z][\x2d0-9a-z]*)$`)

var specPatternDigest = regexp.MustCompile(`^(?:[\x2d0-9A-Z\x5fa-z]+)$`)

var specPatternAmountString = regexp.MustCompile(`^(?:\x2d?(?:0|[1-9][0-9]*)(?:\x2e[0-9]+)?)$`)

var specPatternDigestField = regexp.MustCompile(`^(?:sha256\x3a[0-9a-f]{64})$`)

var specPatternTimestamp = regexp.MustCompile(`^(?:[0-9]{4}\x2d(?:0[1-9]|1[0-2])\x2d(?:0[1-9]|[12][0-9]|3[01])T(?:[01][0-9]|2[0-3])\x3a[0-5][0-9]\x3a[0-5][0-9](?:\x2e[0-9]+)?Z)$`)

var specPatternFormatName = regexp.MustCompile(`^(?:[a-z][\x2d0-9a-z]*)$`)

var specPatternCodeSystem = regexp.MustCompile(`^(?:[A-Za-z][\x2b\x2d\x2e0-9A-Za-z]*\x3a(?:[\x21\x24\x26-\x3b\x3d\x3f-Z\x5fa-z\x7e]|\x25[0-9A-Fa-f][0-9A-Fa-f])+)$`)

var specPatternArrayIndex = regexp.MustCompile(`^(?:(?:0|[1-9][0-9]*))$`)

var specPatternHexSha256 = regexp.MustCompile(`^(?:[0-9a-f]{64})$`)

// specPatterns is every whole-string matcher above, keyed by core.json pattern id.
var specPatterns = map[string]*regexp.Regexp{"caid": specPatternCaid, "action_type": specPatternActionType, "suite": specPatternSuite, "digest": specPatternDigest, "amount_string": specPatternAmountString, "digest_field": specPatternDigestField, "timestamp": specPatternTimestamp, "format_name": specPatternFormatName, "code_system": specPatternCodeSystem, "array_index": specPatternArrayIndex, "hex_sha256": specPatternHexSha256}

// specPatternMaxOctets is the length limit, in octets, checked before a pattern is matched.
var specPatternMaxOctets = map[string]int{"caid": 1024, "action_type": 512, "code_system": 2048}

// specCodeFormats is the whole-string matcher of each registered code format.
var specCodeFormats = map[string]*regexp.Regexp{"icd-10-cm": regexp.MustCompile(`^(?:[A-Z][0-9A-Z]{2}(?:\x2e[0-9A-Z]{1,4})?)$`), "ndc-11": regexp.MustCompile(`^(?:[0-9]{11})$`), "ndc-10-hyphenated": regexp.MustCompile(`^(?:(?:[0-9]{4}\x2d[0-9]{4}\x2d[0-9]{2}|[0-9]{5}\x2d[0-9]{4}\x2d[0-9]|[0-9]{5}\x2d[0-9]{3}\x2d[0-9]{2}))$`), "cpt": regexp.MustCompile(`^(?:[0-9]{4}[0-9A-Z])$`), "hcpcs-level-ii": regexp.MustCompile(`^(?:[A-Z][0-9]{4})$`), "hcpcs": regexp.MustCompile(`^(?:(?:[0-9]{4}[0-9A-Z]|[A-Z][0-9]{4}))$`), "iso-3166-2": regexp.MustCompile(`^(?:[A-Z]{2}\x2d[0-9A-Z]{1,3})$`), "iso20022-external-code": regexp.MustCompile(`^(?:[0-9A-Z]{1,4})$`), "nacha-sec": regexp.MustCompile(`^(?:[0-9A-Z]{3})$`)}

// specSuiteDigestPatterns is each registered suite's digest syntax.
var specSuiteDigestPatterns = map[string]*regexp.Regexp{"jcs-sha256": regexp.MustCompile(`^(?:[\x2d0-9A-Z\x5fa-z]{42}[048AEIMQUYcgkosw])$`), "cbor-sha256": regexp.MustCompile(`^(?:[\x2d0-9A-Z\x5fa-z]{42}[048AEIMQUYcgkosw])$`)}

// specTimestampYear is the byte range [start, end) of the year in a timestamp.
var specTimestampYear = [2]int{0, 4}

// specTimestampMonth is the byte range [start, end) of the month in a timestamp.
var specTimestampMonth = [2]int{5, 7}

// specTimestampDay is the byte range [start, end) of the day in a timestamp.
var specTimestampDay = [2]int{8, 10}

// specLimitJsonTextOctets is core.json limit json_text_octets.
const specLimitJsonTextOctets = 33554432

// specLimitNestingDepth is core.json limit nesting_depth.
const specLimitNestingDepth = 64

// specLimitCanonicalOctets is core.json limit canonical_octets.
const specLimitCanonicalOctets = 16777216

// specLimitMaxSafeInteger is core.json limit max_safe_integer.
const specLimitMaxSafeInteger = 9007199254740991

// specLimitValueCount is core.json limit value_count.
const specLimitValueCount = 33554432

// specLimitDocumentCanonicalOctets is core.json limit document_canonical_octets.
const specLimitDocumentCanonicalOctets = 134217728

// specLimitCaidOctets is core.json limit caid_octets.
const specLimitCaidOctets = 1024

// specLimitActionTypeOctets is core.json limit action_type_octets.
const specLimitActionTypeOctets = 512

// specLimitCodeSystemOctets is core.json limit code_system_octets.
const specLimitCodeSystemOctets = 2048

// specLimitMappingRulesMin is core.json limit mapping_rules_min.
const specLimitMappingRulesMin = 1

// specLimitMappingRulesMax is core.json limit mapping_rules_max.
const specLimitMappingRulesMax = 128

// specLimitMappingPointerOctetsMax is core.json limit mapping_pointer_octets_max.
const specLimitMappingPointerOctetsMax = 2048

// specLimitMappingStringOctetsMin is core.json limit mapping_string_octets_min.
const specLimitMappingStringOctetsMin = 1

// specLimitMappingStringOctetsMax is core.json limit mapping_string_octets_max.
const specLimitMappingStringOctetsMax = 512

// specLimitMappingOmissionReasonOctetsMin is core.json limit mapping_omission_reason_octets_min.
const specLimitMappingOmissionReasonOctetsMin = 1

// specLimitMappingOmissionReasonOctetsMax is core.json limit mapping_omission_reason_octets_max.
const specLimitMappingOmissionReasonOctetsMax = 2048

// specJSONByteOrderMark is the UTF-8 byte order mark a JSON text must not begin with.
var specJSONByteOrderMark = []byte{0xEF, 0xBB, 0xBF}

// specJSONWhitespace is the JSON whitespace set of RFC 8259.
var specJSONWhitespace = []byte{0x20, 0x09, 0x0A, 0x0D}

// specNoncharacterRanges lists the noncharacter code points as inclusive ranges.
var specNoncharacterRanges = [][2]rune{{0xFDD0, 0xFDEF}, {0xFFFE, 0xFFFF}, {0x1FFFE, 0x1FFFF}, {0x2FFFE, 0x2FFFF}, {0x3FFFE, 0x3FFFF}, {0x4FFFE, 0x4FFFF}, {0x5FFFE, 0x5FFFF}, {0x6FFFE, 0x6FFFF}, {0x7FFFE, 0x7FFFF}, {0x8FFFE, 0x8FFFF}, {0x9FFFE, 0x9FFFF}, {0xAFFFE, 0xAFFFF}, {0xBFFFE, 0xBFFFF}, {0xCFFFE, 0xCFFFF}, {0xDFFFE, 0xDFFFF}, {0xEFFFE, 0xEFFFF}, {0xFFFFE, 0xFFFFF}, {0x10FFFE, 0x10FFFF}}

// specSortRankCompute is the rank of each reason after the compute gates.
var specSortRankCompute = map[string]int{"missing_material_field": 3, "mistyped_field": 4, "invalid_amount": 4, "invalid_code": 4, "unknown_suite": 5, "unsupported_number": 6, "unsupported_value": 7}

// specSortRankVerify is the rank of each reason after the verify gates.
var specSortRankVerify = map[string]int{"action_type_mismatch": 4, "definition_mismatch": 5, "unknown_suite": 6, "digest_mismatch": 6, "invalid_object": 7}

// specVerifyDetail is the closed shape of one verification detail. Field
// is "param" (the reason parameter), a fixed field name, or "" (null);
// Observed is "member", "argument", or "" (null).
type specVerifyDetail struct {
	Rule     string
	Field    string
	Observed string
}

// specVerifyDetails is the detail shape of each reason a verification reports.
var specVerifyDetails = map[string]specVerifyDetail{"malformed_caid": {"caid", "", "argument"}, "unknown_suite": {"suite", "", ""}, "malformed_json": {"json-text", "", ""}, "action_type_mismatch": {"action-type-equal", "action_type", "member"}, "definition_mismatch": {"definition-sha256", "", ""}, "digest_mismatch": {"digest-equal", "", ""}, "invalid_action_type": {"action-type", "action_type", "member"}, "unknown_action_type": {"definition-resolution", "", ""}, "invalid_definition": {"definition-conformance", "", ""}, "missing_material_field": {"required-field", "param", "member"}, "mistyped_field": {"field-type", "param", "member"}, "invalid_amount": {"amount-string", "param", "member"}, "invalid_code": {"code-format", "param", "member"}, "unsupported_number": {"number", "", ""}, "unsupported_value": {"data-model", "", ""}}

// specVerifyDetailExpandOmit lists, per expanded reason, the operation reasons the expansion leaves out.
var specVerifyDetailExpandOmit = map[string][]string{"invalid_object": {"unknown_suite"}}

// specFieldTypeJSON is the JSON kind each field type holds.
var specFieldTypeJSON = map[string]string{"string": "string", "amount-string": "string", "digest": "string", "enum": "string", "code": "string", "timestamp": "string", "integer": "number", "boolean": "boolean", "object": "object", "array": "array"}

// specFieldTypeMembers lists the definition members specific to each field type.
var specFieldTypeMembers = map[string][]string{"string": {}, "amount-string": {}, "digest": {}, "enum": {"values", "values_ref", "values_snapshot", "values_sha256"}, "code": {"code_system", "format"}, "timestamp": {}, "integer": {}, "boolean": {}, "object": {}, "array": {}}

// specFieldTypeRequiredMembers maps "type.member" to the pattern id its value must match.
var specFieldTypeRequiredMembers = map[string]string{"code.code_system": "code_system", "code.format": "format_name"}

// specFieldTypePattern is the whole-string matcher of each grammar-checked field type.
var specFieldTypePattern = map[string]*regexp.Regexp{"amount-string": specPatternAmountString, "digest": specPatternDigestField, "timestamp": specPatternTimestamp}

// specFieldTypeCalendarCheck names the calendar check a field type applies after its grammar.
var specFieldTypeCalendarCheck = map[string]string{"timestamp": "day_within_month"}

// specFieldTypePatternRefusal is the reason for a string that fails a field type's grammar.
var specFieldTypePatternRefusal = map[string]string{"amount-string": "invalid_amount", "digest": "mistyped_field", "timestamp": "mistyped_field"}

// specCodeFormatRefusal is the reason for a string that fails its code format.
const specCodeFormatRefusal = "invalid_code"

// specCodeUnregisteredFormatRefusal is the reason for a present code field whose format is not registered.
const specCodeUnregisteredFormatRefusal = "mistyped_field"

// specUnknownFieldTypeRefusal is the reason for a present field whose type is not registered.
const specUnknownFieldTypeRefusal = "mistyped_field"

// specDefinitionFieldLists names the two field lists of a definition, in order.
var specDefinitionFieldLists = []string{"required_fields", "optional_fields"}

// specRequiredFieldsMin is the minimum length of required_fields.
const specRequiredFieldsMin = 1

// specFieldCommonMembers lists the members every field entry may carry.
var specFieldCommonMembers = []string{"name", "type", "notes"}

// specFieldNameMinLength is the minimum length of a field name.
const specFieldNameMinLength = 1

// specFieldNameForbiddenCodePoints lists code points a field name must not contain.
var specFieldNameForbiddenCodePoints = []rune{58}

// specReservedFieldNames lists names no field entry may take.
var specReservedFieldNames = []string{"action_type"}

// specProjectionFieldMembersExcluded lists field-entry members the projection drops.
var specProjectionFieldMembersExcluded = []string{"notes"}

// specDefinitionDigestPrefix prefixes the hexadecimal definition_sha256.
const specDefinitionDigestPrefix = "sha256:"

// specResolutionNone is the reason when no definition matches the action type.
const specResolutionNone = "unknown_action_type"

// specResolutionConflict is the reason when matching definitions differ in definition_sha256.
const specResolutionConflict = "invalid_definition"

// specResolutionNonconforming is the reason when a matching definition does not conform.
const specResolutionNonconforming = "invalid_definition"

// specEnumInlinePrefix begins the compact inline enum form.
const specEnumInlinePrefix = "inline:"

// specEnumInlineSeparator separates compact inline enum members.
const specEnumInlineSeparator = "|"

// specEnumInlineTrim lists the characters trimmed from compact inline enum members.
var specEnumInlineTrim = []string{" "}

// specMappingProfileVersion is the @version of a v1 mapping profile.
const specMappingProfileVersion = "CAID-MAPPING-PROFILE-v1"

// specMappingProfileMembers lists the members a mapping profile may carry.
var specMappingProfileMembers = []string{"@version", "profile_id", "source_format", "target_action_type", "loss_policy", "omitted_source_fields", "material_source_paths", "rules"}

// specMappingSourceFormatMembers lists the members a mapping source format may carry.
var specMappingSourceFormatMembers = []string{"media_type", "schema", "version"}

// specMappingRuleMembers lists the members a mapping rule may carry.
var specMappingRuleMembers = []string{"source_path", "target_field", "transform"}

// specMappingOmittedSourceFieldMembers lists the members a mapping omitted source field may carry.
var specMappingOmittedSourceFieldMembers = []string{"source_path", "reason"}

// specMappingOptionalProfileMembers lists the profile members that may be absent.
var specMappingOptionalProfileMembers = []string{"omitted_source_fields"}

// specMappingMemberRule constrains the profile member at Path ("*" is every
// array element). Limits are core.json limit values, 0 when absent; Rule is
// an ABNF rule name, Closed a closed set ("transforms", "loss_policies").
type specMappingMemberRule struct {
	Path      []string
	JSON      string
	Rule      string
	Closed    string
	Reserved  []string
	MinOctets int
	MaxOctets int
	MinItems  int
	MaxItems  int
}

// specMappingMemberRules lists the profile member rules in order.
var specMappingMemberRules = []specMappingMemberRule{
	{Path: []string{"profile_id"}, JSON: "string", Rule: "", Closed: "", Reserved: []string{}, MinOctets: 1, MaxOctets: 512, MinItems: 0, MaxItems: 0},
	{Path: []string{"source_format", "media_type"}, JSON: "string", Rule: "", Closed: "", Reserved: []string{}, MinOctets: 1, MaxOctets: 512, MinItems: 0, MaxItems: 0},
	{Path: []string{"source_format", "schema"}, JSON: "string", Rule: "", Closed: "", Reserved: []string{}, MinOctets: 1, MaxOctets: 512, MinItems: 0, MaxItems: 0},
	{Path: []string{"source_format", "version"}, JSON: "string", Rule: "", Closed: "", Reserved: []string{}, MinOctets: 1, MaxOctets: 512, MinItems: 0, MaxItems: 0},
	{Path: []string{"target_action_type"}, JSON: "string", Rule: "", Closed: "", Reserved: []string{}, MinOctets: 1, MaxOctets: 512, MinItems: 0, MaxItems: 0},
	{Path: []string{"loss_policy"}, JSON: "string", Rule: "", Closed: "loss_policies", Reserved: []string{}, MinOctets: 0, MaxOctets: 0, MinItems: 0, MaxItems: 0},
	{Path: []string{"rules"}, JSON: "array", Rule: "", Closed: "", Reserved: []string{}, MinOctets: 0, MaxOctets: 0, MinItems: 1, MaxItems: 128},
	{Path: []string{"rules", "*", "source_path"}, JSON: "string", Rule: "source-path", Closed: "", Reserved: []string{}, MinOctets: 0, MaxOctets: 2048, MinItems: 0, MaxItems: 0},
	{Path: []string{"rules", "*", "target_field"}, JSON: "string", Rule: "field-name", Closed: "", Reserved: []string{"action_type"}, MinOctets: 0, MaxOctets: 0, MinItems: 0, MaxItems: 0},
	{Path: []string{"rules", "*", "transform"}, JSON: "string", Rule: "", Closed: "transforms", Reserved: []string{}, MinOctets: 0, MaxOctets: 0, MinItems: 0, MaxItems: 0},
	{Path: []string{"material_source_paths"}, JSON: "array", Rule: "", Closed: "", Reserved: []string{}, MinOctets: 0, MaxOctets: 0, MinItems: 1, MaxItems: 0},
	{Path: []string{"material_source_paths", "*"}, JSON: "string", Rule: "source-path", Closed: "", Reserved: []string{}, MinOctets: 0, MaxOctets: 2048, MinItems: 0, MaxItems: 0},
	{Path: []string{"omitted_source_fields"}, JSON: "array", Rule: "", Closed: "", Reserved: []string{}, MinOctets: 0, MaxOctets: 0, MinItems: 0, MaxItems: 0},
	{Path: []string{"omitted_source_fields", "*", "source_path"}, JSON: "string", Rule: "source-path", Closed: "", Reserved: []string{}, MinOctets: 0, MaxOctets: 2048, MinItems: 0, MaxItems: 0},
	{Path: []string{"omitted_source_fields", "*", "reason"}, JSON: "string", Rule: "", Closed: "", Reserved: []string{}, MinOctets: 1, MaxOctets: 2048, MinItems: 0, MaxItems: 0},
}

// specMappingUnique lists the member paths whose values must be distinct.
var specMappingUnique = [][]string{[]string{"rules", "*", "source_path"}, []string{"rules", "*", "target_field"}, []string{"material_source_paths", "*"}, []string{"omitted_source_fields", "*", "source_path"}}

// specMappingEqualSets lists member path pairs whose value sets must be equal.
var specMappingEqualSets = [][2][]string{{[]string{"rules", "*", "source_path"}, []string{"material_source_paths", "*"}}}

// specMappingDisjoint lists member path pairs whose value sets must not intersect.
var specMappingDisjoint = [][2][]string{{[]string{"omitted_source_fields", "*", "source_path"}, []string{"rules", "*", "source_path"}}}

// specMappingTransforms lists the registered transforms.
var specMappingTransforms = []string{"copy", "sha256-utf8", "sha256-jcs", "sha256-hex-to-digest"}

// specMappingTransformPattern is the whole-string matcher a transform requires of its string input.
var specMappingTransformPattern = map[string]*regexp.Regexp{"sha256-hex-to-digest": specPatternHexSha256}

// specMappingLossPolicies lists the registered loss policies.
var specMappingLossPolicies = []string{"no-material-field-loss", "declared-source-semantic-loss"}

// specMappingLossPolicyOmissions is what each loss policy requires of omitted_source_fields.
var specMappingLossPolicyOmissions = map[string]string{"no-material-field-loss": "absent_or_empty", "declared-source-semantic-loss": "non_empty"}

// specMappingReasonRank orders mapping reasons: stages A and B sort together by it.
var specMappingReasonRank = map[string]int{"invalid_mapping_profile": 0, "unknown_action_type": 1, "invalid_definition": 2, "unmapped_material_field": 3, "native_verification_required": 4, "mapping_profile_unpinned": 5, "source_format_mismatch": 6, "source_not_object": 7, "source_not_canonicalizable": 8, "declared_source_semantic_loss": 9, "invalid_source_path": 10, "missing_source_field": 11, "source_value_type_mismatch": 12, "source_value_not_canonicalizable": 13, "unknown_transform": 14, "mapped_action": 15}

// specMappingComparisonPrefixes lists the side prefixes of comparison reasons, in order.
var specMappingComparisonPrefixes = []string{"left", "right"}

// specMappingPrefixedVerdict is the verdict of a comparison that carries side-prefixed reasons.
const specMappingPrefixedVerdict = "INDETERMINATE"

// specMappingReasonVerdicts is the verdict each comparison reason carries.
var specMappingReasonVerdicts = map[string]string{"target_action_type_mismatch": "INDETERMINATE", "material_projection_mismatch": "NOT_EQUIVALENT"}

// specMappingFaultReasons lists codes a conforming mapper never emits.
var specMappingFaultReasons = []string{"unexpected_mapping_error", "invalid_mapped_action"}
