// SPDX-License-Identifier: Apache-2.0
// Observe-scope guard for the control plane.
//
// The self-serve pilot bootstrap mints a real ep_live_ API key so a caller can
// run traffic through the gate in OBSERVE mode and read its own report. That
// credential must never reach tenant administration (SSO, SCIM, enrollment,
// or another control-plane surface).

import { authEntityObserveProfile } from '@/lib/auth-projections.js';

/**
 * Return true for both current and pre-marker pilot identities.
 *
 * Current pilot entities carry metadata.pilot_sandbox/scope. The legacy shape
 * is retained here because keys issued before the marker migration still
 * authenticate until the reconciliation migration has run. The identity
 * binding and route-generated pilot naming convention avoid treating an
 * ordinary tenant key as an observe credential during rollout.
 *
 * @param {{ entity?: object }} auth authenticateRequest() result
 * @returns {boolean}
 */
export function isObserveScoped(auth) {
  const entity = authEntityObserveProfile(auth);
  if (!entity) return false;

  const meta = entity.metadata && typeof entity.metadata === 'object' && !Array.isArray(entity.metadata)
    ? entity.metadata
    : null;
  if (meta && (meta.scope === 'observe' || meta.pilot_sandbox === true)) return true;

  // Legacy public pilot rows predate the metadata marker. These fields are
  // generated by /api/pilot/sandbox/provision. A false positive only denies a
  // control-plane capability; it cannot grant one.
  return entity.entity_type === 'agent'
    && entity.organization_id === entity.entity_id
    && typeof entity.display_name === 'string'
    && entity.display_name.startsWith('Pilot · ')
    && typeof entity.description === 'string'
    && entity.description.startsWith('Observe-mode pilot sandbox for ');
}

/**
 * Fail-closed control-plane guard. Returns a 403 response for an observe-mode
 * pilot key, or null when the caller may proceed.
 *
 * @param {object} auth authenticateRequest() result
 * @param {(status:number, code:string, detail:string) => Response} epProblem
 * @returns {Response|null}
 */
export function refuseObserveScope(auth, epProblem) {
  if (isObserveScoped(auth)) {
    return epProblem(
      403,
      'observe_scope_forbidden',
      'This is an observe-mode pilot sandbox key. It can run actions through the gate and read its own report, but it cannot access the control plane (SSO, SCIM, or tenant administration).',
    );
  }
  return null;
}
